/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ArchiveSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "CindyApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ProductionSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "Suggestions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
