#!/usr/bin/env bash
# ==============================================================================
# brainsOS: Multi-Agent Fleet Manifest Synchronization & Orchestration Engine
# Renders docker-compose.agents.yml and config/caddy/agents.caddy from config/agents.yaml.
# Scaffolds host storage partitions, permissions, and LiteLLM virtual keys.
# ==============================================================================

set -euo pipefail

# Visual styling
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "${SCRIPT_DIR}" rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "${REPO_ROOT}" ]; then
  _check_dir="${SCRIPT_DIR}"
  while [ "${_check_dir}" != "/" ] && [ -n "${_check_dir}" ]; do
    if [ -f "${_check_dir}/config/agents.yaml" ] || [ -d "${_check_dir}/.git" ]; then
      REPO_ROOT="${_check_dir}"
      break
    fi
    _check_dir="$(dirname "${_check_dir}")"
  done
  [ -z "${REPO_ROOT}" ] && REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
fi

cd "${REPO_ROOT}"

CALLER_BRAINSOS_DOMAIN="${BRAINSOS_DOMAIN:-}"
CALLER_ACME_DNS_PROVIDER="${ACME_DNS_PROVIDER:-}"

# Load environment variables
if [ -f .env ]; then
  set -a
  . ./.env
  set +a
elif [ -f .env.example ]; then
  set -a
  . ./.env.example
  set +a
fi

[ -n "${CALLER_BRAINSOS_DOMAIN}" ] && BRAINSOS_DOMAIN="${CALLER_BRAINSOS_DOMAIN}"
[ -n "${CALLER_ACME_DNS_PROVIDER}" ] && ACME_DNS_PROVIDER="${CALLER_ACME_DNS_PROVIDER}"
export BRAINSOS_DOMAIN="${BRAINSOS_DOMAIN:-brainsos.local}"
export ACME_DNS_PROVIDER="${ACME_DNS_PROVIDER:-}"

if [ -n "${GITHUB_TOKEN_CINDY:-}" ] && [ -z "${GITHUB_BASIC_AUTH_CINDY:-}" ]; then
  GITHUB_BASIC_AUTH_CINDY="$(printf 'x-access-token:%s' "${GITHUB_TOKEN_CINDY}" | base64 | tr -d '\r\n')"
  export GITHUB_BASIC_AUTH_CINDY
  if [ -f .env ] && grep -q "^GITHUB_BASIC_AUTH_CINDY=" .env; then
    sed -i.bak "s|^GITHUB_BASIC_AUTH_CINDY=.*|GITHUB_BASIC_AUTH_CINDY=${GITHUB_BASIC_AUTH_CINDY}|" .env && rm -f .env.bak
  elif [ -f .env ]; then
    echo "GITHUB_BASIC_AUTH_CINDY=${GITHUB_BASIC_AUTH_CINDY}" >> .env
  fi
fi

if [ -z "${MANIFEST_FILE:-}" ]; then
  if [ -f "${REPO_ROOT}/config/agents.local.yaml" ]; then
    MANIFEST_FILE="${REPO_ROOT}/config/agents.local.yaml"
    log_info "Using host-local fleet manifest override: config/agents.local.yaml"
  elif [ -f "${REPO_ROOT}/config/agents.override.yaml" ]; then
    MANIFEST_FILE="${REPO_ROOT}/config/agents.override.yaml"
    log_info "Using host-local fleet manifest override: config/agents.override.yaml"
  else
    MANIFEST_FILE="${REPO_ROOT}/config/agents.yaml"
  fi
fi
export MANIFEST_FILE
OUTPUT_COMPOSE="${REPO_ROOT}/docker-compose.agents.yml"
OUTPUT_CADDY="${REPO_ROOT}/config/caddy/agents.caddy"
OUTPUT_TLS="${REPO_ROOT}/config/caddy/tls_policy.caddy"
OUTPUT_CONTINUE="${REPO_ROOT}/config/editor/continue_config.yaml"
OUTPUT_CONTINUE_JSON="${REPO_ROOT}/config/editor/continue_config.json"

# Ensure python3 with yaml is available
PYTHON_BIN="python3"
if [ -x "${REPO_ROOT}/.venv/bin/python" ]; then
  PYTHON_BIN="${REPO_ROOT}/.venv/bin/python"
fi

if ! ${PYTHON_BIN} -c "import yaml" >/dev/null 2>&1; then
  log_error "Python PyYAML package is required to parse ${MANIFEST_FILE}."
  exit 1
fi

if [ ! -f "${MANIFEST_FILE}" ]; then
  log_error "Fleet manifest not found at ${MANIFEST_FILE}."
  exit 1
fi

MODE="${1:-sync}"

# ------------------------------------------------------------------------------
# Core Generator in Python
# ------------------------------------------------------------------------------
render_manifest() {
  MANIFEST_FILE="${MANIFEST_FILE}" BRAINSOS_DOMAIN="${BRAINSOS_DOMAIN:-brainsos.local}" ACME_DNS_PROVIDER="${ACME_DNS_PROVIDER:-}" ${PYTHON_BIN} - << 'EOF'
import os
import sys
import json
import yaml

repo_root = os.getcwd()
manifest_path = os.environ.get("MANIFEST_FILE", os.path.join(repo_root, "config", "agents.yaml"))

with open(manifest_path, "r", encoding="utf-8") as f:
    manifest = yaml.safe_load(f)

manifest_rel = os.path.relpath(manifest_path, repo_root)
agents = manifest.get("agents", [])
enabled_agents = [a for a in agents if a.get("enabled", True)]
brainsos_domain = os.environ.get("BRAINSOS_DOMAIN", "brainsos.local")
acme_dns_provider = os.environ.get("ACME_DNS_PROVIDER", "")

# 1. Render docker-compose.agents.yml
compose_lines = [
    "# ==============================================================================",
    "# brainsOS: Declarative Multi-Agent Fleet Services",
    "# Auto-generated by scripts/control/sync-agents.sh from config/agents.yaml.",
    "# DO NOT EDIT DIRECTLY. Make changes in config/agents.yaml and re-run sync.",
    "# ==============================================================================",
    "",
    "services:",
]

for agent in enabled_agents:
    agent_id = agent["id"]
    name = agent.get("name", f"Agent {agent_id}")
    runtime = agent.get("runtime", "hermes")
    port = agent.get("comms", {}).get("port", 8642)
    dash_port = agent.get("comms", {}).get("dashboard_port", 9119)
    sig_config = agent.get("comms", {}).get("signal", {})
    signal_enabled = sig_config.get("enabled", False)
    sig_http_url = sig_config.get("http_url", "http://signal-cli:8080")
    sig_account_env = sig_config.get("account_env", f"SIGNAL_ACCOUNT_{agent_id.upper().replace('-', '_')}")
    sig_users_env = sig_config.get("allowed_users_env", f"SIGNAL_ALLOWED_USERS_{agent_id.upper().replace('-', '_')}")
    tg_config = agent.get("comms", {}).get("telegram", {})
    telegram_enabled = tg_config.get("enabled", False)
    tg_bot = tg_config.get("bot_name", tg_config.get("bot_profile", f"@{agent_id}_bot"))
    tg_token_env = tg_config.get("token_env", f"TELEGRAM_BOT_TOKEN_{agent_id.upper().replace('-', '_')}")
    tg_users_env = tg_config.get("allowed_users_env", f"TELEGRAM_ALLOWED_USERS_{agent_id.upper().replace('-', '_')}")

    mail_config = agent.get("comms", {}).get("email", {})
    mail_address = mail_config.get("address", f"{agent_id}@brainsos.local")
    mail_user_env = mail_config.get("user_env", f"{agent_id.upper().replace('-', '_')}_MAIL_USER")
    mail_pass_env = mail_config.get("password_env", f"{agent_id.upper().replace('-', '_')}_MAIL_PASSWORD")
    default_pass = f"brainsos_{agent_id.lower().replace('-', '_')}_mail_secret_change_me"
    mail_env_lines = [
        f"      - AGENT_MAIL_USER=${{{mail_user_env}:-{mail_address}}}",
        f"      - AGENT_MAIL_PASSWORD=${{{mail_pass_env}:-{default_pass}}}",
        f"      - BRAINSOS_MAIL_SMTP_HOST=mail-server",
        f"      - BRAINSOS_MAIL_SMTP_PORT=25",
        f"      - BRAINSOS_MAIL_IMAP_HOST=mail-server",
        f"      - BRAINSOS_MAIL_IMAP_PORT=143",
    ]

    mem_path = agent.get("memory", {}).get("path", f"./data/agent_memories/{agent_id}")
    work_path = agent.get("workspace", {}).get("path", f"./data/agent_workspaces/{agent_id}")
    site_path = agent.get("workspace", {}).get("site_path")
    canvas_mount = agent.get("workspace", {}).get("canvas_mount", "/app/html")
    key_name = agent.get("routing", {}).get("virtual_key", f"{agent_id.upper().replace('-', '_')}_LITELLM_KEY")
    api_key_name = agent.get("comms", {}).get("api_key_env", f"HERMES_API_{agent_id.upper().replace('-', '_')}_KEY")

    volume_lines = [
        f"      # L3: Memory Plane (pure OKF markdown)",
        f"      - {mem_path}:/memories",
        f"      # Read-only configuration",
        f"      - ./config/hermes:/app/config:ro",
        f"      # L3: Unprivileged Workspace Sandbox",
        f"      - {work_path}:/opt/data",
        f"      - {work_path}:/workspace",
    ]

    if site_path:
        volume_lines.append(f"      # Dedicated Public HTML Canvas")
        volume_lines.append(f"      - {site_path}:{canvas_mount}")
        protected_paths = agent.get("workspace", {}).get("protected_paths", [])
        for prot_path in protected_paths:
            prot_clean = prot_path.strip("/")
            volume_lines.append(f"      # Masked / Read-Only Protected Path")
            volume_lines.append(f"      - {site_path}/{prot_clean}:{canvas_mount}/{prot_clean}:ro")
        write_safe_root = f"/opt/data:/workspace:{canvas_mount}"
        workspace_dir_env = "/workspace"
    else:
        write_safe_root = "/opt/data"
        workspace_dir_env = "/opt/data"

    git_config = agent.get("git", {})
    git_env_lines = []
    if git_config:
        git_user = git_config.get("user_name", f"Agent {agent_id}")
        git_email = git_config.get("user_email", f"{agent_id}@brainsos.local")
        git_env_lines = [
            f"      - GIT_AUTHOR_NAME={git_user}",
            f"      - GIT_AUTHOR_EMAIL={git_email}",
            f"      - GIT_COMMITTER_NAME={git_user}",
            f"      - GIT_COMMITTER_EMAIL={git_email}",
            f"      - GIT_TERMINAL_PROMPT=0",
        ]

    # L4: Tool Egress Gateway & Inspection Proxy Configuration
    egress_config = agent.get("egress", {})
    egress_enabled = egress_config.get("enabled", True)
    egress_env_lines = []
    depends_lines = [
        f"    depends_on:",
        f"      - signal-cli",
        f"      - mail-server",
    ]
    if egress_enabled:
        http_proxy = egress_config.get("http_proxy", "http://brainsos-net-egress-proxy:8082")
        https_proxy = egress_config.get("https_proxy", "http://brainsos-net-egress-proxy:8082")
        no_proxy = egress_config.get("no_proxy", "localhost,127.0.0.1,host.docker.internal,proxy.local,litellm,signal-cli,brainsos-signal-cli,brainsos-net-signal-cli,brainsos-litellm-db,brainsos-infra-litellm-db,mail-server,brainsos-mail-server,brainsos-net-mail-server,.brainsos.local,*.brainsos.local,brainsos.local,.brainsos.internal,*.brainsos.internal,brainsos.internal")
        egress_env_lines = [
            f"      - HTTP_PROXY={http_proxy}",
            f"      - HTTPS_PROXY={https_proxy}",
            f"      - http_proxy={http_proxy}",
            f"      - https_proxy={https_proxy}",
            f"      - NO_PROXY={no_proxy}",
            f"      - no_proxy={no_proxy}",
            f"      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt",
            f"      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt",
            f"      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt",
        ]
        volume_lines.append(f"      # Tool Egress Proxy CA Certificate Mount (Read-Only)")
        volume_lines.append(f"      - tool_egress_proxy_data:/etc/ssl/mitmproxy:ro")
        depends_lines.append(f"      - tool-egress-proxy")


    compose_lines.extend([
        f"  # --------------------------------------------------------------------------",
        f"  # L2: Agent Core Unit: {name} ({agent_id})",
        f"  # --------------------------------------------------------------------------",
        f"  agent-{agent_id}:",
        f"    build:",
        f"      context: .",
        f"      dockerfile: docker/hermes/Dockerfile",
        f"    image: brainsos-hermes:latest",
        f"    container_name: brainsos-agent-{agent_id}",
        f"    restart: unless-stopped",
        f"    security_opt:",
        f"      - \"no-new-privileges:true\"",
        f"    ports:",
        f"      - \"127.0.0.1:{port}:{port}\"",
        f"      - \"127.0.0.1:{dash_port}:{dash_port}\"",
        f"    extra_hosts:",
        f"      - \"host.docker.internal:host-gateway\"",
        f"      - \"proxy.local:host-gateway\"",
        f"      - \"litellm:host-gateway\"",
        f"      - \"langfuse.brainsos.local:${{LANGFUSE_HOST_IP:-host-gateway}}\"",
        f"    volumes:",
    ] + volume_lines + [
        f"    working_dir: /opt/data",
        f"    environment:",
        f"      - PUID=${{PUID:-1000}}",
        f"      - PGID=${{PGID:-1000}}",
        f"      - HERMES_AGENT_ID={agent_id}",
        f"      - AGENT_ID={agent_id}",
        f"      - HERMES_DASHBOARD=1",
        f"      - HERMES_PORT={port}",
        f"      - HERMES_DASHBOARD_PORT={dash_port}",
        f"      - HERMES_DASHBOARD_BASIC_AUTH_USERNAME=${{HERMES_DASHBOARD_USER:-admin}}",
        f"      - HERMES_DASHBOARD_BASIC_AUTH_PASSWORD=${{HERMES_DASHBOARD_PASSWORD:-brainsos_admin_secret}}",
        f"      - HERMES_LITELLM_KEY=${{{key_name}:-sk-brainsos-{agent_id}-key}}",
        f"      - CUSTOM_API_KEY=${{{key_name}:-sk-brainsos-{agent_id}-key}}",
        f"      - OPENAI_API_KEY=${{{key_name}:-sk-brainsos-{agent_id}-key}}",
        f"      - OPENAI_BASE_URL=http://proxy.local:${{LITELLM_PORT:-4000}}/v1",
        f"      - PROXY_URL=http://proxy.local:${{LITELLM_PORT:-4000}}/v1",
        f"      - LITELLM_URL=http://proxy.local:${{LITELLM_PORT:-4000}}/v1",
        f"      - HERMES_STREAM_STALE_TIMEOUT=600",
        f"      - HERMES_STREAM_READ_TIMEOUT=600",
        f"      - MEMORY_DIR=/memories",
        f"      - WORKSPACE_DIR={workspace_dir_env}",
        f"      - HERMES_WRITE_SAFE_ROOT={write_safe_root}",
        f"      - INFERENCE_NUM_CTX=${{INFERENCE_NUM_CTX:-4096}}",
        f"      - HERMES_GATEWAY_BOOTSTRAP_STATE=running",
        f"      - API_SERVER_HOST=0.0.0.0",
        f"      - API_SERVER_PORT={port}",
        f"      - API_SERVER_KEY=${{{api_key_name}:-}}",
        f"      - SIGNAL_HTTP_URL={sig_http_url}",
        f"      - SIGNAL_ACCOUNT=${{SIGNAL_ACCOUNT:-}}" if sig_account_env == "SIGNAL_ACCOUNT" else f"      - SIGNAL_ACCOUNT=${{{sig_account_env}:-${{SIGNAL_ACCOUNT:-}}}}",
        f"      - SIGNAL_ALLOWED_USERS=${{SIGNAL_ALLOWED_USERS:-}}" if sig_users_env == "SIGNAL_ALLOWED_USERS" else f"      - SIGNAL_ALLOWED_USERS=${{{sig_users_env}:-${{SIGNAL_ALLOWED_USERS:-}}}}",
        f"      - TELEGRAM_BOT_NAME={tg_bot}",
        f"      - TELEGRAM_BOT_TOKEN=${{{tg_token_env}:-${{TELEGRAM_BOT_TOKEN:-}}}}",
        f"      - TELEGRAM_ALLOWED_USERS=${{{tg_users_env}:-${{TELEGRAM_ALLOWED_USERS:-}}}}",
        f"      - LANGFUSE_HOST=${{LANGFUSE_HOST:-http://langfuse.brainsos.local:${{LANGFUSE_PORT:-3001}}}}",
        f"      - LANGFUSE_PUBLIC_KEY=${{LANGFUSE_PUBLIC_KEY:-}}",
        f"      - LANGFUSE_SECRET_KEY=${{LANGFUSE_SECRET_KEY:-}}",
        f"      - LANGFUSE_OTEL_AUTH=${{LANGFUSE_OTEL_AUTH:-}}",
        f"      - OTEL_SERVICE_NAME=hermes-{agent_id}",
        f"      - OTEL_RESOURCE_ATTRIBUTES=service.name=hermes-{agent_id},agent.id={agent_id},session.id=brainsos-{agent_id}-default",
    ] + git_env_lines + mail_env_lines + egress_env_lines + [
        f"    command: [\"sleep\", \"infinity\"]",
    ] + depends_lines + [
        f"    networks:",
        f"      - brainsos-ingress",
        f"      - brainsos-internal",
        "",
    ])

# Dynamic Ingress Gateway network aliases for Operator IDE reachability
caddy_aliases = []
for a in enabled_agents:
    sub = a.get("comms", {}).get("subdomain") or f"{a['id']}.brainsos.local"
    sub_prefix = sub.split(".")[0]
    caddy_aliases.append(f"api.{sub_prefix}.{brainsos_domain}")
    if brainsos_domain != "brainsos.local":
        caddy_aliases.append(f"api.{sub_prefix}.brainsos.local")

compose_lines.extend([
    "  # --------------------------------------------------------------------------",
    "  # L7: Ingress Gateway Network Aliases for Operator IDE Reachability",
    "  # --------------------------------------------------------------------------",
    "  caddy:",
    "    networks:",
    "      brainsos-operator-net:",
    "        aliases:",
] + [f"          - {alias}" for alias in sorted(set(caddy_aliases))] + [
    "",
])

has_egress_volume = any(a.get("egress", {}).get("enabled", True) for a in enabled_agents)
if has_egress_volume:
    compose_lines.extend([
        "volumes:",
        "  tool_egress_proxy_data:",
        "    name: brainsos_tool_egress_proxy_data",
        "",
    ])

# 2. Render config/caddy/agents.caddy
caddy_lines = [
    "# ==============================================================================",
    "# brainsOS: Ingress Reverse Proxy Routes for Agent Units (L1: Comms & UX)",
    "# Auto-generated by scripts/control/sync-agents.sh from config/agents.yaml.",
    "# DO NOT EDIT DIRECTLY. Make changes in config/agents.yaml and re-run sync.",
    "# ==============================================================================",
    "",
]

for idx, agent in enumerate(enabled_agents):
    agent_id = agent["id"]
    name = agent.get("name", f"Agent {agent_id}")
    port = agent.get("comms", {}).get("port", 8642)
    dash_port = agent.get("comms", {}).get("dashboard_port", 9119)
    subdomain = agent.get("comms", {}).get("subdomain", f"{agent_id}.brainsos.local")

    # Clean host routing - zero legacy debt
    sub_prefix = subdomain.split(".")[0]
    agent_domain = f"{sub_prefix}.{brainsos_domain}"

    # Public domain routes using brainsos_tls (Route 53 ACME or internal)
    public_hosts = [f"http://{agent_domain}", f"https://{agent_domain}"]
    for extra in agent.get("comms", {}).get("extra_domains", []):
        public_hosts.extend([f"http://{extra}", f"https://{extra}"])

    # Localhost and .brainsos.local routes strictly using internal CA (never sent to ACME)
    localhost_hosts = [f"http://{sub_prefix}.localhost", f"https://{sub_prefix}.localhost"]
    if brainsos_domain != "brainsos.local":
        localhost_hosts.extend([f"http://{sub_prefix}.brainsos.local", f"https://{sub_prefix}.brainsos.local"])
    if agent_id != sub_prefix:
        localhost_hosts.extend([f"http://{agent_id}.localhost", f"https://{agent_id}.localhost"])

    # Public API routes using brainsos_tls
    public_api_hosts = [f"http://api.{agent_domain}", f"https://api.{agent_domain}"]
    for extra in agent.get("comms", {}).get("extra_domains", []):
        public_api_hosts.extend([f"http://api.{extra}", f"https://api.{extra}"])

    # Localhost and .brainsos.local API routes strictly using internal CA
    localhost_api_hosts = [f"http://api.{sub_prefix}.localhost", f"https://api.{sub_prefix}.localhost"]
    if brainsos_domain != "brainsos.local":
        localhost_api_hosts.extend([f"http://api.{sub_prefix}.brainsos.local", f"https://api.{sub_prefix}.brainsos.local"])
    if agent_id != sub_prefix:
        localhost_api_hosts.extend([f"http://api.{agent_id}.localhost", f"https://api.{agent_id}.localhost"])


    hosts_str = ", ".join(public_hosts)
    local_hosts_str = ", ".join(localhost_hosts)
    api_hosts_str = ", ".join(public_api_hosts)
    local_api_hosts_str = ", ".join(localhost_api_hosts)

    caddy_lines.extend([
        f"# ------------------------------------------------------------------------------",
        f"# Agent Unit: {name} ({agent_id}) - Dashboard & Console",
        f"# ------------------------------------------------------------------------------",
        f"{hosts_str} {{",
        f"	import brainsos_tls",
        f"	encode gzip zstd",
        f"	log {{",
        f"		output stdout",
        f"		format console",
        f"	}}",
        f"	reverse_proxy brainsos-agent-{agent_id}:{dash_port} {{",
        f"		flush_interval -1",
        f"	}}",
        f"}}",
        f"",
        f"{local_hosts_str} {{",
        f"	tls internal",
        f"	encode gzip zstd",
        f"	log {{",
        f"		output stdout",
        f"		format console",
        f"	}}",
        f"	reverse_proxy brainsos-agent-{agent_id}:{dash_port} {{",
        f"		flush_interval -1",
        f"	}}",
        f"}}",
        f"",
        f"# ------------------------------------------------------------------------------",
        f"# Agent Unit: {name} ({agent_id}) - OpenAI-Compatible API",
        f"# ------------------------------------------------------------------------------",
        f"{api_hosts_str} {{",
        f"	import brainsos_tls",
        f"	encode gzip zstd",
        f"	log {{",
        f"		output stdout",
        f"		format console",
        f"	}}",
        f"	reverse_proxy brainsos-agent-{agent_id}:{port} {{",
        f"		flush_interval -1",
        f"	}}",
        f"}}",
        f"",
        f"{local_api_hosts_str} {{",
        f"	tls internal",
        f"	encode gzip zstd",
        f"	log {{",
        f"		output stdout",
        f"		format console",
        f"	}}",
        f"	reverse_proxy brainsos-agent-{agent_id}:{port} {{",
        f"		flush_interval -1",
        f"	}}",
        f"}}",
        f"",
    ])

# 3. Render config/editor/continue_config.yaml
continue_models = [
    {
        "name": "brainsOS Core (LiteLLM)",
        "provider": "openai",
        "model": "brainsos-core",
        "apiBase": "http://litellm:4000/v1",
        "apiKey": "${OPERATOR_LITELLM_KEY}",
        "roles": ["chat", "edit", "apply"]
    }
]

for agent in enabled_agents:
    agent_id = agent["id"]
    agent_name = agent.get("name", agent_id).split(" - ")[0]
    subdomain = agent.get("comms", {}).get("subdomain", f"{agent_id}.brainsos.local")
    sub_prefix = subdomain.split(".")[0]
    api_host = f"api.{sub_prefix}.{brainsos_domain}"
    api_key_name = agent.get("comms", {}).get("api_key_env", f"HERMES_API_{agent_id.upper().replace('-', '_')}_KEY")
    continue_models.append({
        "name": f"{agent_name} (Agent API)",
        "provider": "openai",
        "model": "hermes-agent",
        "apiBase": f"http://{api_host}/v1",
        "apiKey": f"${{{api_key_name}}}",
        "roles": ["chat"]
    })

continue_cfg = {
    "name": "brainsOS Operator IDE",
    "version": "1.0.0",
    "schema": "v1",
    "models": continue_models
}

tls_lines = [
    "# ==============================================================================",
    "# brainsOS: TLS Policy Snippet",
    "# Auto-generated by scripts/control/sync-agents.sh from environment configuration.",
    "# DO NOT EDIT DIRECTLY. Make changes in .env and re-run sync.",
    "# ==============================================================================",
    "(brainsos_tls) {",
]
if acme_dns_provider.lower() == "route53" and not brainsos_domain.endswith(".local") and brainsos_domain != "localhost":
    tls_lines.extend([
        "	tls {",
        "		dns route53",
        "	}",
    ])
else:
    tls_lines.append("	tls internal")
tls_lines.append("}")
rendered_tls_policy = "\n".join(tls_lines).strip() + "\n"

rendered_compose = "\n".join(compose_lines).strip() + "\n"
rendered_caddy = "\n".join(caddy_lines).strip() + "\n"
rendered_continue = yaml.safe_dump(continue_cfg, sort_keys=False)
rendered_continue_json = json.dumps(continue_cfg, indent=2) + "\n"

# Output separator for bash parsing
print("__START_COMPOSE__")
sys.stdout.write(rendered_compose)
print("__END_COMPOSE__")
print("__START_CADDY__")
sys.stdout.write(rendered_caddy)
print("__END_CADDY__")
print("__START_TLS__")
sys.stdout.write(rendered_tls_policy)
print("__END_TLS__")
print("__START_CONTINUE__")
sys.stdout.write(rendered_continue)
print("__END_CONTINUE__")
print("__START_CONTINUE_JSON__")
sys.stdout.write(rendered_continue_json)
print("__END_CONTINUE_JSON__")
EOF
}

# ------------------------------------------------------------------------------
# Action: Drift Detection (--check)
# ------------------------------------------------------------------------------
if [ "${MODE}" = "--check" ]; then
  log_info "Verifying fleet manifest drift against rendered files..."
  
  RENDERED_OUTPUT=$(render_manifest)
  EXPECTED_COMPOSE=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_COMPOSE__/,/__END_COMPOSE__/p' | sed '1d;$d')
  EXPECTED_CADDY=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_CADDY__/,/__END_CADDY__/p' | sed '1d;$d')
  EXPECTED_TLS=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_TLS__/,/__END_TLS__/p' | sed '1d;$d')
  EXPECTED_CONTINUE=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_CONTINUE__/,/__END_CONTINUE__/p' | sed '1d;$d')
  EXPECTED_CONTINUE_JSON=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_CONTINUE_JSON__/,/__END_CONTINUE_JSON__/p' | sed '1d;$d')

  DRIFT_DETECTED=0

  if [ ! -f "${OUTPUT_COMPOSE}" ]; then
    log_error "Missing file: ${OUTPUT_COMPOSE}"
    DRIFT_DETECTED=1
  else
    ACTUAL_COMPOSE=$(cat "${OUTPUT_COMPOSE}")
    if [ "${ACTUAL_COMPOSE}" != "${EXPECTED_COMPOSE}" ]; then
      log_error "Drift detected in ${OUTPUT_COMPOSE}!"
      diff -u <(echo "${ACTUAL_COMPOSE}") <(echo "${EXPECTED_COMPOSE}") || true
      DRIFT_DETECTED=1
    fi
  fi

  if [ ! -f "${OUTPUT_CADDY}" ]; then
    log_error "Missing file: ${OUTPUT_CADDY}"
    DRIFT_DETECTED=1
  else
    ACTUAL_CADDY=$(cat "${OUTPUT_CADDY}")
    if [ "${ACTUAL_CADDY}" != "${EXPECTED_CADDY}" ]; then
      log_error "Drift detected in ${OUTPUT_CADDY}!"
      diff -u <(echo "${ACTUAL_CADDY}") <(echo "${EXPECTED_CADDY}") || true
      DRIFT_DETECTED=1
    fi
  fi

  if [ ! -f "${OUTPUT_TLS}" ]; then
    log_error "Missing file: ${OUTPUT_TLS}"
    DRIFT_DETECTED=1
  else
    ACTUAL_TLS=$(cat "${OUTPUT_TLS}")
    if [ "${ACTUAL_TLS}" != "${EXPECTED_TLS}" ]; then
      log_error "Drift detected in ${OUTPUT_TLS}!"
      diff -u <(echo "${ACTUAL_TLS}") <(echo "${EXPECTED_TLS}") || true
      DRIFT_DETECTED=1
    fi
  fi

  if [ ! -f "${OUTPUT_CONTINUE}" ]; then
    log_error "Missing file: ${OUTPUT_CONTINUE}"
    DRIFT_DETECTED=1
  else
    ACTUAL_CONTINUE=$(cat "${OUTPUT_CONTINUE}")
    if [ "${ACTUAL_CONTINUE}" != "${EXPECTED_CONTINUE}" ]; then
      log_error "Drift detected in ${OUTPUT_CONTINUE}!"
      diff -u <(echo "${ACTUAL_CONTINUE}") <(echo "${EXPECTED_CONTINUE}") || true
      DRIFT_DETECTED=1
    fi
  fi

  if [ ! -f "${OUTPUT_CONTINUE_JSON}" ]; then
    log_error "Missing file: ${OUTPUT_CONTINUE_JSON}"
    DRIFT_DETECTED=1
  else
    ACTUAL_CONTINUE_JSON=$(cat "${OUTPUT_CONTINUE_JSON}")
    if [ "${ACTUAL_CONTINUE_JSON}" != "${EXPECTED_CONTINUE_JSON}" ]; then
      log_error "Drift detected in ${OUTPUT_CONTINUE_JSON}!"
      diff -u <(echo "${ACTUAL_CONTINUE_JSON}") <(echo "${EXPECTED_CONTINUE_JSON}") || true
      DRIFT_DETECTED=1
    fi
  fi

  if [ ${DRIFT_DETECTED} -eq 0 ]; then
    log_success "✓ Fleet configuration is 100% in sync with $(basename "${MANIFEST_FILE}")."
    exit 0
  else
    log_error "Fleet drift check failed! Please run './scripts/control/sync-agents.sh' to reconcile."
    exit 1
  fi
fi

# ------------------------------------------------------------------------------
# Helper: Provision Virtual Keys in LiteLLM Control Plane Database
# ------------------------------------------------------------------------------
provision_virtual_keys() {
  LITELLM_PORT="${LITELLM_PORT:-4000}"
  LITELLM_MASTER_KEY="${LITELLM_MASTER_KEY:-}"
  LITELLM_URL="http://127.0.0.1:${LITELLM_PORT}"

  if ! curl -s -o /dev/null -w "%{http_code}" "${LITELLM_URL}/health/liveness" | grep -qE '^(200|401|405)'; then
    log_info "LiteLLM control plane is not currently running. Virtual keys will be seeded upon control plane boot."
    return 0
  fi

  if [ -z "${LITELLM_MASTER_KEY}" ]; then
    log_warn "LITELLM_MASTER_KEY is unset; skipping LiteLLM virtual key seeding."
    return 0
  fi

  log_info "Provisioning fleet virtual keys in LiteLLM Control Plane (${LITELLM_URL})..."

  MANIFEST_FILE="${MANIFEST_FILE}" ${PYTHON_BIN} - << EOF
import os
import urllib.request
import json
import yaml

repo_root = os.getcwd()
manifest_path = os.environ.get("MANIFEST_FILE", os.path.join(repo_root, "config", "agents.yaml"))
with open(manifest_path, "r", encoding="utf-8") as f:
    manifest = yaml.safe_load(f)

master_key = os.environ.get("LITELLM_MASTER_KEY", "")
litellm_url = "${LITELLM_URL}"

for agent in manifest.get("agents", []):
    agent_id = agent["id"]
    budget = float(agent.get("routing", {}).get("budget_monthly_usd", 25.0))
    key_name = agent.get("routing", {}).get("virtual_key", f"{agent_id.upper().replace('-', '_')}_LITELLM_KEY")
    key_val = os.environ.get(key_name, f"sk-brainsos-{agent_id}-key")

    check_url = f"{litellm_url}/key/info?key={key_val}"
    req = urllib.request.Request(check_url, headers={"Authorization": f"Bearer {master_key}"})
    key_exists = False
    try:
        with urllib.request.urlopen(req) as resp:
            if resp.status == 200:
                key_exists = True
    except Exception:
        pass

    key_payload = {
        "key": key_val,
        "key_alias": f"brainsos-agent-{agent_id}",
        "user_id": agent_id,
        "max_budget": budget,
        "models": [],
        "metadata": {
            "agent_id": agent_id,
            "project": "brainsos"
        }
    }
    if not key_exists:
        gen_url = f"{litellm_url}/key/generate"
        payload = json.dumps(key_payload).encode("utf-8")
        gen_req = urllib.request.Request(
            gen_url,
            data=payload,
            headers={
                "Authorization": f"Bearer {master_key}",
                "Content-Type": "application/json"
            }
        )
        try:
            with urllib.request.urlopen(gen_req) as resp:
                print(f"[SUCCESS] Provisioned virtual key for agent '{agent_id}' (alias: brainsos-agent-{agent_id}, budget: \${budget:.2f}).")
        except Exception as e:
            print(f"[WARN] Failed to provision key for '{agent_id}': {e}")
    else:
        update_url = f"{litellm_url}/key/update"
        payload = json.dumps(key_payload).encode("utf-8")
        update_req = urllib.request.Request(
            update_url,
            data=payload,
            headers={
                "Authorization": f"Bearer {master_key}",
                "Content-Type": "application/json"
            }
        )
        try:
            with urllib.request.urlopen(update_req) as resp:
                print(f"[INFO] Synchronized virtual key identity and metadata for agent '{agent_id}' in LiteLLM DB.")
        except Exception:
            print(f"[INFO] Virtual key for agent '{agent_id}' is already registered in LiteLLM DB.")
EOF
}

if [ "${MODE}" = "--provision-keys" ]; then
  provision_virtual_keys
  exit 0
fi

# ------------------------------------------------------------------------------
# Action: Full Synchronization
# ------------------------------------------------------------------------------
log_info "Synchronizing brainsOS Multi-Agent Fleet from ${MANIFEST_FILE}..."

RENDERED_OUTPUT=$(render_manifest)
EXPECTED_COMPOSE=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_COMPOSE__/,/__END_COMPOSE__/p' | sed '1d;$d')
EXPECTED_CADDY=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_CADDY__/,/__END_CADDY__/p' | sed '1d;$d')
EXPECTED_TLS=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_TLS__/,/__END_TLS__/p' | sed '1d;$d')
EXPECTED_CONTINUE=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_CONTINUE__/,/__END_CONTINUE__/p' | sed '1d;$d')
EXPECTED_CONTINUE_JSON=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_CONTINUE_JSON__/,/__END_CONTINUE_JSON__/p' | sed '1d;$d')

# 1. Write docker-compose.agents.yml
echo "${EXPECTED_COMPOSE}" > "${OUTPUT_COMPOSE}"
log_success "Rendered agent compose topology at ${OUTPUT_COMPOSE}."

# 2. Write config/caddy/agents.caddy and tls_policy.caddy
mkdir -p "${REPO_ROOT}/config/caddy"
echo "${EXPECTED_CADDY}" > "${OUTPUT_CADDY}"
echo "${EXPECTED_TLS}" > "${OUTPUT_TLS}"
log_success "Rendered Caddy ingress configuration at ${OUTPUT_CADDY} and ${OUTPUT_TLS}."

# 3. Write config/editor/continue_config.yaml & continue_config.json
mkdir -p "$(dirname "${OUTPUT_CONTINUE}")"
echo "${EXPECTED_CONTINUE}" > "${OUTPUT_CONTINUE}"
echo "${EXPECTED_CONTINUE_JSON}" > "${OUTPUT_CONTINUE_JSON}"
log_success "Rendered Continue configuration at ${OUTPUT_CONTINUE} and ${OUTPUT_CONTINUE_JSON}."

# 4. Scaffold host storage partitions & permissions for each agent
MANIFEST_FILE="${MANIFEST_FILE}" ${PYTHON_BIN} - << 'EOF'
import os
import shutil
import json
import yaml

repo_root = os.getcwd()
manifest_path = os.environ.get("MANIFEST_FILE", os.path.join(repo_root, "config", "agents.yaml"))
with open(manifest_path, "r", encoding="utf-8") as f:
    manifest = yaml.safe_load(f)

enabled_agents = [a for a in manifest.get("agents", []) if a.get("enabled", True)]

for agent in manifest.get("agents", []):
    agent_id = agent["id"]
    mem_rel = agent.get("memory", {}).get("path", f"./data/agent_memories/{agent_id}")
    work_rel = agent.get("workspace", {}).get("path", f"./data/agent_workspaces/{agent_id}")
    site_rel = agent.get("workspace", {}).get("site_path")

    mem_dir = os.path.abspath(os.path.join(repo_root, mem_rel.lstrip("./")))
    work_dir = os.path.abspath(os.path.join(repo_root, work_rel.lstrip("./")))

    # Automated migration from previous agent identity if renaming
    migrate_from = agent.get("migrate_from")
    if migrate_from:
        old_mem = os.path.abspath(os.path.join(repo_root, "data", "agent_memories", migrate_from))
        if not os.path.exists(old_mem):
            old_mem = os.path.abspath(os.path.join(repo_root, "data", "memories", migrate_from))
        old_work = os.path.abspath(os.path.join(repo_root, "data", "agent_workspaces", migrate_from))
        if not os.path.exists(old_work):
            old_work = os.path.abspath(os.path.join(repo_root, "data", "workspace", migrate_from))
        old_persona_dir = os.path.abspath(os.path.join(repo_root, "config", "hermes", migrate_from))
        new_persona_dir = os.path.abspath(os.path.join(repo_root, "config", "hermes", agent_id))

        if os.path.exists(old_persona_dir) and not os.path.exists(new_persona_dir):
            print(f"[INFO] Migrating Hermes persona from '{migrate_from}' to '{agent_id}'...")
            shutil.copytree(old_persona_dir, new_persona_dir, symlinks=True)

        if os.path.exists(old_mem) and (not os.path.exists(mem_dir) or not os.listdir(mem_dir)):
            print(f"[INFO] Migrating memory partition from '{migrate_from}' to '{agent_id}'...")
            shutil.copytree(old_mem, mem_dir, dirs_exist_ok=True, symlinks=True, ignore=shutil.ignore_patterns(".cache", "*.sock"))

        if os.path.exists(old_work) and (not os.path.exists(work_dir) or not os.listdir(work_dir)):
            print(f"[INFO] Migrating workspace partition from '{migrate_from}' to '{agent_id}'...")
            shutil.copytree(old_work, work_dir, dirs_exist_ok=True, symlinks=True, ignore=shutil.ignore_patterns(".cache", "*.sock"))

    os.makedirs(mem_dir, exist_ok=True)
    os.makedirs(work_dir, exist_ok=True)

    if site_rel:
        for prot_path in agent.get("workspace", {}).get("protected_paths", []):
            prot_clean = prot_path.strip("/")
            prot_full = os.path.abspath(os.path.join(repo_root, site_rel.lstrip("./"), prot_clean))
            os.makedirs(prot_full, exist_ok=True)

    # Seamless migration from legacy tenants directory if present and agents dir does not exist
    legacy_mem_dir = os.path.abspath(os.path.join(repo_root, "data", "memories", "tenants", agent_id))
    if os.path.exists(legacy_mem_dir) and not os.path.exists(mem_dir):
        os.makedirs(os.path.dirname(mem_dir), exist_ok=True)
        shutil.move(legacy_mem_dir, mem_dir)

    # Scaffold memory partition (OKF pure markdown structure)
    for sub in ("knowledge", "rules", "logs"):
        sub_dir = os.path.join(mem_dir, sub)
        os.makedirs(sub_dir, exist_ok=True)
        keep = os.path.join(sub_dir, ".gitkeep")
        if not os.path.exists(keep):
            with open(keep, "w") as f:
                f.write("")

    # Seed universal memory purity guardrail rule
    rules_tmpl = os.path.join(repo_root, "config", "memories", "rules", "memory_purity_guardrail.md")
    dest_rule = os.path.join(mem_dir, "rules", "memory_purity_guardrail.md")
    if os.path.exists(rules_tmpl) and not os.path.exists(dest_rule):
        shutil.copyfile(rules_tmpl, dest_rule)

    # Seed persona (SOUL.md) to both memory plane and Hermes runtime workspace
    persona_path = agent.get("persona")
    if persona_path and os.path.exists(os.path.join(repo_root, persona_path)):
        src_persona = os.path.join(repo_root, persona_path)
        shutil.copyfile(src_persona, os.path.join(mem_dir, "SOUL.md"))
        shutil.copyfile(src_persona, os.path.join(work_dir, "SOUL.md"))

    # Seed subagents if configured
    subagents = agent.get("subagents", [])
    subagents_mem_dir = os.path.join(mem_dir, "subagents")
    subagents_work_dir = os.path.join(work_dir, "subagents")
    if subagents:
        os.makedirs(subagents_mem_dir, exist_ok=True)
        os.makedirs(subagents_work_dir, exist_ok=True)
        for sub in subagents:
            sub_id = sub.get("id")
            sub_persona_path = sub.get("persona")
            if sub_id and sub_persona_path and os.path.exists(os.path.join(repo_root, sub_persona_path)):
                src_sub_persona = os.path.join(repo_root, sub_persona_path)
                dest_sub_mem = os.path.join(subagents_mem_dir, sub_id)
                dest_sub_work = os.path.join(subagents_work_dir, sub_id)
                os.makedirs(dest_sub_mem, exist_ok=True)
                os.makedirs(dest_sub_work, exist_ok=True)
                shutil.copyfile(src_sub_persona, os.path.join(dest_sub_mem, "SOUL.md"))
                shutil.copyfile(src_sub_persona, os.path.join(dest_sub_work, "SOUL.md"))
        with open(os.path.join(work_dir, "subagents.json"), "w", encoding="utf-8") as sf:
            json.dump(subagents, sf, indent=2)
        with open(os.path.join(mem_dir, "subagents.json"), "w", encoding="utf-8") as sf:
            json.dump(subagents, sf, indent=2)

    # Scaffold workspace sandbox (tools, skills, cron, and runtime memories)
    for sub in ("skills", "plugins", "signal", "cron", "memories"):
        os.makedirs(os.path.join(work_dir, sub), exist_ok=True)

    # Scaffold brainsos-subagents plugin into workspace if subagents configured
    if subagents:
        src_plugin = os.path.join(repo_root, "docker", "hermes", "plugins", "brainsos-subagents")
        dest_plugin = os.path.join(work_dir, "plugins", "brainsos-subagents")
        if os.path.exists(src_plugin):
            if os.path.exists(dest_plugin):
                shutil.rmtree(dest_plugin)
            shutil.copytree(src_plugin, dest_plugin)

    # Scaffold brainsos-mail plugin into workspace
    src_mail_plugin = os.path.join(repo_root, "docker", "hermes", "plugins", "brainsos-mail")
    dest_mail_plugin = os.path.join(work_dir, "plugins", "brainsos-mail")
    if os.path.exists(src_mail_plugin):
        if os.path.exists(dest_mail_plugin):
            shutil.rmtree(dest_mail_plugin)
        shutil.copytree(src_mail_plugin, dest_mail_plugin)

    # Seed initial Hermes working memory files if not present
    ws_memories_dir = os.path.join(work_dir, "memories")
    mem_file = os.path.join(ws_memories_dir, "MEMORY.md")
    user_file = os.path.join(ws_memories_dir, "USER.md")
    if not os.path.exists(mem_file):
        with open(mem_file, "w", encoding="utf-8") as f:
            f.write(f"# {agent.get('name', agent_id)} — Working Memory\n\nActive context and execution notes.\n")
    if not os.path.exists(user_file):
        with open(user_file, "w", encoding="utf-8") as f:
            f.write(f"# User Profile\n\nFacts and preferences learned about the user.\n")

    keep = os.path.join(work_dir, ".gitkeep")
    if not os.path.exists(keep):
        with open(keep, "w") as f:
            f.write("")

    # Scaffold dedicated web app site / HTML canvas repository if configured
    if site_rel:
        site_dir = os.path.abspath(os.path.join(repo_root, site_rel.lstrip("./")))
        os.makedirs(site_dir, exist_ok=True)
        repo_url = agent.get("workspace", {}).get("repo_url")
        git_dir = os.path.join(site_dir, ".git")
        if repo_url and not os.path.exists(git_dir):
            import subprocess
            try:
                existing_items = [i for i in os.listdir(site_dir) if i != ".gitkeep"]
                if not existing_items:
                    keep_file = os.path.join(site_dir, ".gitkeep")
                    if os.path.exists(keep_file):
                        os.remove(keep_file)
                    subprocess.run(["git", "clone", repo_url, site_dir], check=True, capture_output=True)
                else:
                    subprocess.run(["git", "-C", site_dir, "init"], check=True, capture_output=True)
                    subprocess.run(["git", "-C", site_dir, "remote", "add", "origin", repo_url], check=True, capture_output=True)
                    subprocess.run(["git", "-C", site_dir, "fetch", "origin"], check=True, capture_output=True)
                    subprocess.run(["git", "-C", site_dir, "checkout", "-f", "main"], check=True, capture_output=True)
            except Exception as ge:
                print(f"[WARN] Git repository binding for {site_dir} encountered: {ge}")

        # Configure local git identity in site_dir if git config provided
        git_conf = agent.get("git", {})
        if os.path.exists(git_dir) and git_conf:
            import subprocess
            u_name = git_conf.get("user_name")
            u_email = git_conf.get("user_email")
            if u_name:
                subprocess.run(["git", "-C", site_dir, "config", "user.name", u_name], capture_output=True)
            if u_email:
                subprocess.run(["git", "-C", site_dir, "config", "user.email", u_email], capture_output=True)

    # Seed agent git config in work_dir if configured
    git_conf = agent.get("git", {})
    if git_conf:
        gitconfig_path = os.path.join(work_dir, ".gitconfig")
        u_name = git_conf.get("user_name", f"Agent {agent_id}")
        u_email = git_conf.get("user_email", f"{agent_id}@brainsos.local")
        with open(gitconfig_path, "w", encoding="utf-8") as gf:
            gf.write(
                f"[user]\n\tname = {u_name}\n\temail = {u_email}\n"
                f"[safe]\n\tdirectory = *\n"
                f"[core]\n\taskPass = \"\"\n"
            )

    # Render Hermes cron jobs if configured
    cron_jobs = agent.get("cron", [])
    if cron_jobs:
        cron_file = os.path.join(work_dir, "cron", "jobs.json")
        jobs_data = []
        for c in cron_jobs:
            jobs_data.append({
                "id": c.get("id", f"{agent_id}-job"),
                "name": c.get("name", c.get("id")),
                "cron_expr": c.get("schedule", "0 2 * * *"),
                "prompt": c.get("prompt", ""),
                "enabled": True,
                "created_at": "2026-09-12T00:00:00Z"
            })
        with open(cron_file, "w", encoding="utf-8") as jf:
            json.dump(jobs_data, jf, indent=2)

    # Seed Hermes configuration with agent identity and default model
    tmpl_config = os.path.join(repo_root, "config", "hermes", "config.yaml")
    dest_config = os.path.join(work_dir, "config.yaml")
    if os.path.exists(tmpl_config):
        with open(tmpl_config, "r", encoding="utf-8") as tf:
            cfg = yaml.safe_load(tf)
        cfg["agent"] = {"name": agent_id}
        default_model = agent.get("models", {}).get("default")
        if default_model and "model" in cfg:
            cfg["model"]["default"] = default_model
        # Seed per-agent OpenTelemetry resource attributes for Langfuse service distinction
        if "monitoring" in cfg:
            if "resource_attributes" not in cfg["monitoring"]:
                cfg["monitoring"]["resource_attributes"] = {}
            cfg["monitoring"]["resource_attributes"]["service.name"] = f"hermes-{agent_id}"
            cfg["monitoring"]["resource_attributes"]["agent.id"] = agent_id
            cfg["monitoring"]["resource_attributes"]["session.id"] = f"brainsos-{agent_id}-default"
        # Seed default session header into custom provider
        if "providers" in cfg and "custom" in cfg["providers"]:
            if "extra_headers" not in cfg["providers"]["custom"]:
                cfg["providers"]["custom"]["extra_headers"] = {}
            cfg["providers"]["custom"]["extra_headers"]["x-litellm-session-id"] = f"brainsos-{agent_id}-default"
        # Seed per-agent Telegram platform settings
        tg_config = agent.get("comms", {}).get("telegram", {})
        if "platforms" in cfg and "telegram" in cfg["platforms"]:
            cfg["platforms"]["telegram"]["enabled"] = tg_config.get("enabled", False)
            cfg["platforms"]["telegram"]["bot_name"] = tg_config.get("bot_name", f"@{agent_id}_bot")
        # Seed per-agent Signal platform settings
        sig_config = agent.get("comms", {}).get("signal", {})
        if "platforms" in cfg and "signal" in cfg["platforms"]:
            cfg["platforms"]["signal"]["enabled"] = sig_config.get("enabled", False)
            if sig_config.get("http_url"):
                cfg["platforms"]["signal"]["http_url"] = sig_config.get("http_url")
        # Ensure brainsos-subagents plugin is enabled if subagents are configured
        if subagents:
            if "plugins" not in cfg:
                cfg["plugins"] = {"enabled": ["hermes-okf"]}
            if "enabled" not in cfg["plugins"]:
                cfg["plugins"]["enabled"] = ["hermes-okf"]
            if "brainsos-subagents" not in cfg["plugins"]["enabled"]:
                cfg["plugins"]["enabled"].append("brainsos-subagents")
        # Ensure brainsos-mail plugin is enabled
        if "plugins" not in cfg:
            cfg["plugins"] = {"enabled": ["hermes-okf"]}
        if "enabled" not in cfg["plugins"]:
            cfg["plugins"]["enabled"] = ["hermes-okf"]
        if "brainsos-mail" not in cfg["plugins"]["enabled"]:
            cfg["plugins"]["enabled"].append("brainsos-mail")
        # Ensure email platform gateway auto-reply is disabled
        if "platforms" not in cfg:
            cfg["platforms"] = {}
        if "email" not in cfg["platforms"]:
            cfg["platforms"]["email"] = {}
        cfg["platforms"]["email"]["enabled"] = False
        # Ensure tool_search dynamic deferral is disabled so model directly sees all tools
        if "tools" not in cfg:
            cfg["tools"] = {}
        if "tool_search" not in cfg["tools"]:
            cfg["tools"]["tool_search"] = {"enabled": "off"}
        else:
            cfg["tools"]["tool_search"]["enabled"] = "off"
        with open(dest_config, "w", encoding="utf-8") as df:
            yaml.safe_dump(cfg, df, sort_keys=False)

    # Seed initial gateway_state.json so s6 auto-starts gateway-default
    gw_state = os.path.join(work_dir, "gateway_state.json")
    if not os.path.exists(gw_state):
        with open(gw_state, "w", encoding="utf-8") as gf:
            gf.write('{"desired_state":"running","gateway_state":"running"}\n')

    print(f"[SUCCESS] Scaffolded host partitions for '{agent_id}':")
    print(f"  - Memory:    {mem_dir}")
    print(f"  - Workspace: {work_dir}")
    if site_rel:
        print(f"  - Site:      {os.path.abspath(os.path.join(repo_root, site_rel.lstrip('./')))}")

# 3B. Render dynamic PKM fleet memory index
index_lines = [
    "# brainsOS: Multi-Agent Fleet Memory Plane\n",
    "Welcome to the **brainsOS Memory Plane**—the human-auditable, decoupled knowledge and governance hub for autonomous agent execution.\n",
    "This workspace mounts the host filesystem (`/memories`) using the **Open Knowledge Format (OKF)**: pure, human-readable flat-file Markdown.\n",
    "---\n",
    "## 🧭 Multi-Agent Fleet Navigation\n"
]
for idx, a in enumerate(enabled_agents, 1):
    a_id = a["id"]
    a_name = a.get("name", a_id)
    index_lines.append(f"### {idx}. [[agents/{a_id}/SOUL|{a_name}]]\n")
    index_lines.append(f"- **Soul & Persona**: [[agents/{a_id}/SOUL|SOUL.md]]\n")
    subagents = a.get("subagents", [])
    for sub in subagents:
        sub_id = sub.get("id")
        sub_name = sub.get("name", sub_id)
        index_lines.append(f"  - **Sub-Agent ({sub_id})**: [[agents/{a_id}/subagents/{sub_id}/SOUL|{sub_name}]]\n")
    index_lines.append(f"- **Knowledge Base**: [[agents/{a_id}/knowledge/|knowledge/]]\n")
    index_lines.append(f"- **Operator Rules**: [[agents/{a_id}/rules/|rules/]]\n")
    index_lines.append(f"- **Session Logs**: [[agents/{a_id}/logs/|logs/]]\n")

index_lines.append("---\n")
index_lines.append("> [!NOTE]\n> **Memory Purity Enforcement**: Only Markdown (`.md`) files are allowed in this space. Binary files, SQLite databases, package caches, and virtualenvs are strictly barred to ensure zero-trust human auditability.\n")
index_content = "\n".join(index_lines)

targets = [os.path.join(repo_root, "config", "memories", "index.md")]
if os.path.exists(os.path.join(repo_root, "data", "agent_memories")):
    targets.append(os.path.join(repo_root, "data", "agent_memories", "index.md"))
elif os.path.exists(os.path.join(repo_root, "data", "memories")):
    targets.append(os.path.join(repo_root, "data", "memories", "index.md"))
else:
    targets.append(os.path.join(repo_root, "data", "agent_memories", "index.md"))

for target_idx in targets:
    os.makedirs(os.path.dirname(target_idx), exist_ok=True)
    with open(target_idx, "w", encoding="utf-8") as f:
        f.write(index_content)
EOF

# 4. Enforce permissions (chmod 775 on workspaces/memories/comms and preserve file executables)
chmod -R 775 "${REPO_ROOT}/data/agent_workspaces" "${REPO_ROOT}/data/agent_memories" "${REPO_ROOT}/data/comms" 2>/dev/null || true
chmod -R 775 "${REPO_ROOT}/data/workspace" "${REPO_ROOT}/data/memories" 2>/dev/null || true
if [ -d "${REPO_ROOT}/apps" ]; then
  find "${REPO_ROOT}/apps" -type d -exec chmod 775 {} + 2>/dev/null || true
  chmod -R ug+rw "${REPO_ROOT}/apps" 2>/dev/null || true
  if [ -d "${REPO_ROOT}/apps/cindypawford/infra/node_modules/.bin" ]; then
    chmod +x "${REPO_ROOT}/apps/cindypawford/infra/node_modules/.bin/"* 2>/dev/null || true
  fi
  if [ -f "${REPO_ROOT}/apps/cindypawford/infra/node_modules/typescript/bin/tsc" ]; then
    chmod +x "${REPO_ROOT}/apps/cindypawford/infra/node_modules/typescript/bin/tsc" 2>/dev/null || true
  fi
fi

# 5. Provision Virtual Keys
provision_virtual_keys

# 6. Reload or Restart Caddy Ingress if running
if docker compose ps -q caddy >/dev/null 2>&1 && [ -n "$(docker compose ps -q caddy 2>/dev/null)" ]; then
  log_info "Reloading Caddy ingress gateway to activate routes..."
  if ! docker compose exec -T caddy caddy reload --config /etc/caddy/Caddyfile 2>/dev/null; then
    log_info "Admin API disabled; ensuring Caddy container is up to date..."
    docker compose up -d --no-deps caddy >/dev/null 2>&1 || log_warn "Failed to update Caddy container."
  fi
fi

log_success "Multi-agent fleet synchronization complete!"
