#!/usr/bin/env bash
# ==============================================================================
# Project Titan: Multi-Agent Fleet Manifest Synchronization & Orchestration Engine
# Renders docker-compose.agents.yml and config/caddy/agents.caddy from config/agents.yaml.
# Scaffolds host storage partitions, permissions, and LiteLLM virtual keys.
# ==============================================================================

set -euo pipefail

# Visual styling
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "${SCRIPT_DIR}" rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "${REPO_ROOT}" ]; then
  _check_dir="${SCRIPT_DIR}"
  while [ "${_check_dir}" != "/" ] && [ -n "${_check_dir}" ]; do
    if [ -f "${_check_dir}/config/agents.yaml" ] || [ -d "${_check_dir}/.git" ]; then
      REPO_ROOT="${_check_dir}"
      break
    fi
    _check_dir="$(dirname "${_check_dir}")"
  done
  [ -z "${REPO_ROOT}" ] && REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
fi

cd "${REPO_ROOT}"

# Load environment variables
if [ -f .env ]; then
  set -a
  . ./.env
  set +a
elif [ -f .env.example ]; then
  set -a
  . ./.env.example
  set +a
fi

if [ -n "${GITHUB_TOKEN_CINDY:-}" ] && [ -z "${GITHUB_BASIC_AUTH_CINDY:-}" ]; then
  GITHUB_BASIC_AUTH_CINDY="$(printf 'x-access-token:%s' "${GITHUB_TOKEN_CINDY}" | base64 | tr -d '\r\n')"
  export GITHUB_BASIC_AUTH_CINDY
  if [ -f .env ] && grep -q "^GITHUB_BASIC_AUTH_CINDY=" .env; then
    sed -i.bak "s|^GITHUB_BASIC_AUTH_CINDY=.*|GITHUB_BASIC_AUTH_CINDY=${GITHUB_BASIC_AUTH_CINDY}|" .env && rm -f .env.bak
  elif [ -f .env ]; then
    echo "GITHUB_BASIC_AUTH_CINDY=${GITHUB_BASIC_AUTH_CINDY}" >> .env
  fi
fi

if [ -z "${MANIFEST_FILE:-}" ]; then
  if [ -f "${REPO_ROOT}/config/agents.local.yaml" ]; then
    MANIFEST_FILE="${REPO_ROOT}/config/agents.local.yaml"
    log_info "Using host-local fleet manifest override: config/agents.local.yaml"
  elif [ -f "${REPO_ROOT}/config/agents.override.yaml" ]; then
    MANIFEST_FILE="${REPO_ROOT}/config/agents.override.yaml"
    log_info "Using host-local fleet manifest override: config/agents.override.yaml"
  else
    MANIFEST_FILE="${REPO_ROOT}/config/agents.yaml"
  fi
fi
export MANIFEST_FILE
OUTPUT_COMPOSE="${REPO_ROOT}/docker-compose.agents.yml"
OUTPUT_CADDY="${REPO_ROOT}/config/caddy/agents.caddy"

# Ensure python3 with yaml is available
PYTHON_BIN="python3"
if [ -x "${REPO_ROOT}/.venv/bin/python" ]; then
  PYTHON_BIN="${REPO_ROOT}/.venv/bin/python"
fi

if ! ${PYTHON_BIN} -c "import yaml" >/dev/null 2>&1; then
  log_error "Python PyYAML package is required to parse ${MANIFEST_FILE}."
  exit 1
fi

if [ ! -f "${MANIFEST_FILE}" ]; then
  log_error "Fleet manifest not found at ${MANIFEST_FILE}."
  exit 1
fi

MODE="${1:-sync}"

# ------------------------------------------------------------------------------
# Core Generator in Python
# ------------------------------------------------------------------------------
render_manifest() {
  MANIFEST_FILE="${MANIFEST_FILE}" ${PYTHON_BIN} - << 'EOF'
import os
import sys
import yaml

repo_root = os.getcwd()
manifest_path = os.environ.get("MANIFEST_FILE", os.path.join(repo_root, "config", "agents.yaml"))

with open(manifest_path, "r", encoding="utf-8") as f:
    manifest = yaml.safe_load(f)

manifest_rel = os.path.relpath(manifest_path, repo_root)
agents = manifest.get("agents", [])
enabled_agents = [a for a in agents if a.get("enabled", True)]

# 1. Render docker-compose.agents.yml
compose_lines = [
    "# ==============================================================================",
    "# Project Titan: Declarative Multi-Agent Fleet Services",
    f"# Auto-generated by scripts/control/sync-agents.sh from {manifest_rel}.",
    f"# DO NOT EDIT DIRECTLY. Make changes in {manifest_rel} and re-run sync.",
    "# ==============================================================================",
    "",
    "services:",
]

for agent in enabled_agents:
    agent_id = agent["id"]
    name = agent.get("name", f"Agent {agent_id}")
    runtime = agent.get("runtime", "hermes")
    port = agent.get("comms", {}).get("port", 8642)
    dash_port = agent.get("comms", {}).get("dashboard_port", 9119)
    signal_enabled = agent.get("comms", {}).get("signal", {}).get("enabled", False)
    tg_config = agent.get("comms", {}).get("telegram", {})
    telegram_enabled = tg_config.get("enabled", False)
    tg_bot = tg_config.get("bot_name", tg_config.get("bot_profile", f"@{agent_id}_bot"))
    tg_token_env = tg_config.get("token_env", f"TELEGRAM_BOT_TOKEN_{agent_id.upper().replace('-', '_')}")
    tg_users_env = tg_config.get("allowed_users_env", f"TELEGRAM_ALLOWED_USERS_{agent_id.upper().replace('-', '_')}")

    mem_path = agent.get("memory", {}).get("path", f"./data/memories/{agent_id}")
    work_path = agent.get("workspace", {}).get("path", f"./data/workspace/{agent_id}")
    site_path = agent.get("workspace", {}).get("site_path")
    canvas_mount = agent.get("workspace", {}).get("canvas_mount", "/app/html")
    key_name = agent.get("routing", {}).get("virtual_key", f"HERMES_{agent_id.upper().replace('-', '_')}_KEY")

    volume_lines = [
        f"      # L3: Memory Plane (pure OKF markdown)",
        f"      - {mem_path}:/memories",
        f"      # Read-only configuration",
        f"      - ./config/hermes:/app/config:ro",
        f"      # L3: Unprivileged Workspace Sandbox",
        f"      - {work_path}:/opt/data",
        f"      - {work_path}:/workspace",
    ]

    if site_path:
        volume_lines.append(f"      # Dedicated Public HTML Canvas")
        volume_lines.append(f"      - {site_path}:{canvas_mount}")
        protected_paths = agent.get("workspace", {}).get("protected_paths", [])
        for prot_path in protected_paths:
            prot_clean = prot_path.strip("/")
            volume_lines.append(f"      # Masked / Read-Only Protected Path")
            volume_lines.append(f"      - {site_path}/{prot_clean}:{canvas_mount}/{prot_clean}:ro")
        write_safe_root = f"/opt/data:/workspace:{canvas_mount}"
        workspace_dir_env = "/workspace"
    else:
        write_safe_root = "/opt/data"
        workspace_dir_env = "/opt/data"

    git_config = agent.get("git", {})
    git_env_lines = []
    if git_config:
        proxy_host = git_config.get("proxy_host", "github-proxy.titan.local")
        git_user = git_config.get("user_name", f"Agent {agent_id}")
        git_email = git_config.get("user_email", f"{agent_id}@titan.local")
        git_env_lines = [
            f"      - GH_HOST={proxy_host}",
            f"      - GIT_AUTHOR_NAME={git_user}",
            f"      - GIT_AUTHOR_EMAIL={git_email}",
            f"      - GIT_COMMITTER_NAME={git_user}",
            f"      - GIT_COMMITTER_EMAIL={git_email}",
            f"      - GIT_TERMINAL_PROMPT=0",
        ]
        volume_lines.append(f"      # In-Transit Caddy Internal PKI CA Mount")
        volume_lines.append(f"      - caddy_data:/etc/ssl/caddy:ro")

    compose_lines.extend([
        f"  # --------------------------------------------------------------------------",
        f"  # L2: Agent Core Unit: {name} ({agent_id})",
        f"  # --------------------------------------------------------------------------",
        f"  agent-{agent_id}:",
        f"    build:",
        f"      context: .",
        f"      dockerfile: docker/hermes/Dockerfile",
        f"    image: titan-hermes:latest",
        f"    container_name: titan-agent-{agent_id}",
        f"    restart: unless-stopped",
        f"    security_opt:",
        f"      - \"no-new-privileges:true\"",
        f"    ports:",
        f"      - \"127.0.0.1:{port}:{port}\"",
        f"      - \"127.0.0.1:{dash_port}:{dash_port}\"",
        f"    extra_hosts:",
        f"      - \"host.docker.internal:host-gateway\"",
        f"      - \"proxy.local:host-gateway\"",
        f"      - \"litellm:host-gateway\"",
        f"      - \"langfuse.titan.local:${{LANGFUSE_HOST_IP:-host-gateway}}\"",
        f"    volumes:",
    ] + volume_lines + [
        f"    working_dir: /opt/data",
        f"    environment:",
        f"      - PUID=${{PUID:-1000}}",
        f"      - PGID=${{PGID:-1000}}",
        f"      - HERMES_DASHBOARD=1",
        f"      - HERMES_PORT={port}",
        f"      - HERMES_DASHBOARD_PORT={dash_port}",
        f"      - HERMES_DASHBOARD_BASIC_AUTH_USERNAME=${{HERMES_DASHBOARD_USER:-admin}}",
        f"      - HERMES_DASHBOARD_BASIC_AUTH_PASSWORD=${{HERMES_DASHBOARD_PASSWORD:-titan_admin_secret}}",
        f"      - HERMES_LITELLM_KEY=${{{key_name}:-sk-titan-{agent_id}-key}}",
        f"      - CUSTOM_API_KEY=${{{key_name}:-sk-titan-{agent_id}-key}}",
        f"      - OPENAI_API_KEY=${{{key_name}:-sk-titan-{agent_id}-key}}",
        f"      - OPENAI_BASE_URL=http://proxy.local:${{LITELLM_PORT:-4000}}/v1",
        f"      - PROXY_URL=http://proxy.local:${{LITELLM_PORT:-4000}}/v1",
        f"      - LITELLM_URL=http://proxy.local:${{LITELLM_PORT:-4000}}/v1",
        f"      - MEMORY_DIR=/memories",
        f"      - WORKSPACE_DIR={workspace_dir_env}",
        f"      - HERMES_WRITE_SAFE_ROOT={write_safe_root}",
        f"      - INFERENCE_NUM_CTX=${{INFERENCE_NUM_CTX:-4096}}",
        f"      - HERMES_GATEWAY_BOOTSTRAP_STATE=running",
        f"      - API_SERVER_HOST=0.0.0.0",
        f"      - API_SERVER_PORT={port}",
        f"      - API_SERVER_KEY=${{API_SERVER_KEY:-}}",
        f"      - SIGNAL_HTTP_URL=http://signal-cli:8080",
        f"      - SIGNAL_ACCOUNT=${{SIGNAL_ACCOUNT:-}}",
        f"      - SIGNAL_ALLOWED_USERS=${{SIGNAL_ALLOWED_USERS:-}}",
        f"      - TELEGRAM_BOT_NAME={tg_bot}",
        f"      - TELEGRAM_BOT_TOKEN=${{{tg_token_env}:-${{TELEGRAM_BOT_TOKEN:-}}}}",
        f"      - TELEGRAM_ALLOWED_USERS=${{{tg_users_env}:-${{TELEGRAM_ALLOWED_USERS:-}}}}",
        f"      - LANGFUSE_OTEL_AUTH=${{LANGFUSE_OTEL_AUTH:-}}",
    ] + git_env_lines + [
        f"    command: [\"sleep\", \"infinity\"]",
        f"    depends_on:",
        f"      - signal-cli",
        f"    networks:",
        f"      - titan-ingress",
        f"      - titan-internal",
        "",
    ])

has_caddy_volume = any(a.get("git") for a in enabled_agents)
if has_caddy_volume:
    compose_lines.extend([
        "volumes:",
        "  caddy_data:",
        "    name: titan_caddy_data",
        "",
    ])

# 2. Render config/caddy/agents.caddy
caddy_lines = [
    "# ==============================================================================",
    "# Project Titan: Ingress Reverse Proxy Routes for Agent Units (L1: Comms & UX)",
    f"# Auto-generated by scripts/control/sync-agents.sh from {manifest_rel}.",
    f"# DO NOT EDIT DIRECTLY. Make changes in {manifest_rel} and re-run sync.",
    "# ==============================================================================",
    "",
]

for idx, agent in enumerate(enabled_agents):
    agent_id = agent["id"]
    name = agent.get("name", f"Agent {agent_id}")
    port = agent.get("comms", {}).get("port", 8642)
    dash_port = agent.get("comms", {}).get("dashboard_port", 9119)
    subdomain = agent.get("comms", {}).get("subdomain", f"{agent_id}.titan.local")

    # Clean host routing - zero legacy debt
    sub_prefix = subdomain.split(".")[0]
    host_list = [f"http://{subdomain}", f"https://{subdomain}", f"http://{sub_prefix}.localhost", f"https://{sub_prefix}.localhost"]
    api_host_list = [f"http://api.{subdomain}", f"https://api.{subdomain}", f"http://api.{sub_prefix}.localhost", f"https://api.{sub_prefix}.localhost"]

    if agent_id != sub_prefix:
        host_list.extend([f"http://{agent_id}.localhost", f"https://{agent_id}.localhost"])
        api_host_list.extend([f"http://api.{agent_id}.localhost", f"https://api.{agent_id}.localhost"])

    hosts_str = ", ".join(host_list)
    api_hosts_str = ", ".join(api_host_list)

    caddy_lines.extend([
        f"# ------------------------------------------------------------------------------",
        f"# Agent Unit: {name} ({agent_id}) - Dashboard & Console",
        f"# ------------------------------------------------------------------------------",
        f"{hosts_str} {{",
        f"	tls internal",
        f"	encode gzip zstd",
        f"	log {{",
        f"		output stdout",
        f"		format console",
        f"	}}",
        f"	reverse_proxy titan-agent-{agent_id}:{dash_port} {{",
        f"		flush_interval -1",
        f"	}}",
        f"}}",
        f"",
        f"# ------------------------------------------------------------------------------",
        f"# Agent Unit: {name} ({agent_id}) - OpenAI-Compatible API",
        f"# ------------------------------------------------------------------------------",
        f"{api_hosts_str} {{",
        f"	tls internal",
        f"	encode gzip zstd",
        f"	log {{",
        f"		output stdout",
        f"		format console",
        f"	}}",
        f"	reverse_proxy titan-agent-{agent_id}:{port} {{",
        f"		flush_interval -1",
        f"	}}",
        f"}}",
        f"",
    ])

rendered_compose = "\n".join(compose_lines).strip() + "\n"
rendered_caddy = "\n".join(caddy_lines).strip() + "\n"

# Output separator for bash parsing
print("__START_COMPOSE__")
sys.stdout.write(rendered_compose)
print("__END_COMPOSE__")
print("__START_CADDY__")
sys.stdout.write(rendered_caddy)
print("__END_CADDY__")
EOF
}

# ------------------------------------------------------------------------------
# Action: Drift Detection (--check)
# ------------------------------------------------------------------------------
if [ "${MODE}" = "--check" ]; then
  log_info "Verifying fleet manifest drift against rendered files..."
  
  RENDERED_OUTPUT=$(render_manifest)
  EXPECTED_COMPOSE=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_COMPOSE__/,/__END_COMPOSE__/p' | sed '1d;$d')
  EXPECTED_CADDY=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_CADDY__/,/__END_CADDY__/p' | sed '1d;$d')

  DRIFT_DETECTED=0

  if [ ! -f "${OUTPUT_COMPOSE}" ]; then
    log_error "Missing file: ${OUTPUT_COMPOSE}"
    DRIFT_DETECTED=1
  else
    ACTUAL_COMPOSE=$(cat "${OUTPUT_COMPOSE}")
    if [ "${ACTUAL_COMPOSE}" != "${EXPECTED_COMPOSE}" ]; then
      log_error "Drift detected in ${OUTPUT_COMPOSE}!"
      diff -u <(echo "${ACTUAL_COMPOSE}") <(echo "${EXPECTED_COMPOSE}") || true
      DRIFT_DETECTED=1
    fi
  fi

  if [ ! -f "${OUTPUT_CADDY}" ]; then
    log_error "Missing file: ${OUTPUT_CADDY}"
    DRIFT_DETECTED=1
  else
    ACTUAL_CADDY=$(cat "${OUTPUT_CADDY}")
    if [ "${ACTUAL_CADDY}" != "${EXPECTED_CADDY}" ]; then
      log_error "Drift detected in ${OUTPUT_CADDY}!"
      diff -u <(echo "${ACTUAL_CADDY}") <(echo "${EXPECTED_CADDY}") || true
      DRIFT_DETECTED=1
    fi
  fi

  if [ ${DRIFT_DETECTED} -eq 0 ]; then
    log_success "✓ Fleet configuration is 100% in sync with $(basename "${MANIFEST_FILE}")."
    exit 0
  else
    log_error "Fleet drift check failed! Please run './scripts/control/sync-agents.sh' to reconcile."
    exit 1
  fi
fi

# ------------------------------------------------------------------------------
# Helper: Provision Virtual Keys in LiteLLM Control Plane Database
# ------------------------------------------------------------------------------
provision_virtual_keys() {
  LITELLM_PORT="${LITELLM_PORT:-4000}"
  LITELLM_MASTER_KEY="${LITELLM_MASTER_KEY:-}"
  LITELLM_URL="http://127.0.0.1:${LITELLM_PORT}"

  if ! curl -s -o /dev/null -w "%{http_code}" "${LITELLM_URL}/health/liveness" | grep -qE '^(200|401|405)'; then
    log_info "LiteLLM control plane is not currently running. Virtual keys will be seeded upon control plane boot."
    return 0
  fi

  if [ -z "${LITELLM_MASTER_KEY}" ]; then
    log_warn "LITELLM_MASTER_KEY is unset; skipping LiteLLM virtual key seeding."
    return 0
  fi

  log_info "Provisioning fleet virtual keys in LiteLLM Control Plane (${LITELLM_URL})..."

  MANIFEST_FILE="${MANIFEST_FILE}" ${PYTHON_BIN} - << EOF
import os
import urllib.request
import json
import yaml

repo_root = os.getcwd()
manifest_path = os.environ.get("MANIFEST_FILE", os.path.join(repo_root, "config", "agents.yaml"))
with open(manifest_path, "r", encoding="utf-8") as f:
    manifest = yaml.safe_load(f)

master_key = os.environ.get("LITELLM_MASTER_KEY", "")
litellm_url = "${LITELLM_URL}"

for agent in manifest.get("agents", []):
    agent_id = agent["id"]
    budget = float(agent.get("routing", {}).get("budget_monthly_usd", 25.0))
    key_name = agent.get("routing", {}).get("virtual_key", f"HERMES_{agent_id.upper().replace('-', '_')}_KEY")
    key_val = os.environ.get(key_name, f"sk-titan-{agent_id}-key")

    check_url = f"{litellm_url}/key/info?key={key_val}"
    req = urllib.request.Request(check_url, headers={"Authorization": f"Bearer {master_key}"})
    key_exists = False
    try:
        with urllib.request.urlopen(req) as resp:
            if resp.status == 200:
                key_exists = True
    except Exception:
        pass

    if not key_exists:
        gen_url = f"{litellm_url}/key/generate"
        payload = json.dumps({
            "key": key_val,
            "key_alias": f"titan-agent-{agent_id}",
            "max_budget": budget,
            "models": []
        }).encode("utf-8")
        gen_req = urllib.request.Request(
            gen_url,
            data=payload,
            headers={
                "Authorization": f"Bearer {master_key}",
                "Content-Type": "application/json"
            }
        )
        try:
            with urllib.request.urlopen(gen_req) as resp:
                print(f"[SUCCESS] Provisioned virtual key for agent '{agent_id}' (alias: titan-agent-{agent_id}, budget: \${budget:.2f}).")
        except Exception as e:
            print(f"[WARN] Failed to provision key for '{agent_id}': {e}")
    else:
        print(f"[INFO] Virtual key for agent '{agent_id}' is already registered in LiteLLM DB.")
EOF
}

if [ "${MODE}" = "--provision-keys" ]; then
  provision_virtual_keys
  exit 0
fi

# ------------------------------------------------------------------------------
# Action: Full Synchronization
# ------------------------------------------------------------------------------
log_info "Synchronizing Project Titan Multi-Agent Fleet from ${MANIFEST_FILE}..."

RENDERED_OUTPUT=$(render_manifest)
EXPECTED_COMPOSE=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_COMPOSE__/,/__END_COMPOSE__/p' | sed '1d;$d')
EXPECTED_CADDY=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_CADDY__/,/__END_CADDY__/p' | sed '1d;$d')

# 1. Write docker-compose.agents.yml
echo "${EXPECTED_COMPOSE}" > "${OUTPUT_COMPOSE}"
log_success "Rendered agent compose topology at ${OUTPUT_COMPOSE}."

# 2. Write config/caddy/agents.caddy
mkdir -p "${REPO_ROOT}/config/caddy"
echo "${EXPECTED_CADDY}" > "${OUTPUT_CADDY}"
log_success "Rendered Caddy ingress configuration at ${OUTPUT_CADDY}."

# 3. Scaffold host storage partitions & permissions for each agent
MANIFEST_FILE="${MANIFEST_FILE}" ${PYTHON_BIN} - << 'EOF'
import os
import shutil
import json
import yaml

repo_root = os.getcwd()
manifest_path = os.environ.get("MANIFEST_FILE", os.path.join(repo_root, "config", "agents.yaml"))
with open(manifest_path, "r", encoding="utf-8") as f:
    manifest = yaml.safe_load(f)

enabled_agents = [a for a in manifest.get("agents", []) if a.get("enabled", True)]

for agent in manifest.get("agents", []):
    agent_id = agent["id"]
    mem_rel = agent.get("memory", {}).get("path", f"./data/memories/agents/{agent_id}")
    work_rel = agent.get("workspace", {}).get("path", f"./data/workspace/{agent_id}")
    site_rel = agent.get("workspace", {}).get("site_path")

    mem_dir = os.path.abspath(os.path.join(repo_root, mem_rel.lstrip("./")))
    work_dir = os.path.abspath(os.path.join(repo_root, work_rel.lstrip("./")))
    os.makedirs(mem_dir, exist_ok=True)
    os.makedirs(work_dir, exist_ok=True)

    if site_rel:
        for prot_path in agent.get("workspace", {}).get("protected_paths", []):
            prot_clean = prot_path.strip("/")
            prot_full = os.path.abspath(os.path.join(repo_root, site_rel.lstrip("./"), prot_clean))
            os.makedirs(prot_full, exist_ok=True)

    # Seamless migration from legacy tenants directory if present and agents dir does not exist
    legacy_mem_dir = os.path.abspath(os.path.join(repo_root, "data", "memories", "tenants", agent_id))
    if os.path.exists(legacy_mem_dir) and not os.path.exists(mem_dir):
        os.makedirs(os.path.dirname(mem_dir), exist_ok=True)
        shutil.move(legacy_mem_dir, mem_dir)

    # Scaffold memory partition (OKF pure markdown structure)
    for sub in ("knowledge", "rules", "logs"):
        sub_dir = os.path.join(mem_dir, sub)
        os.makedirs(sub_dir, exist_ok=True)
        keep = os.path.join(sub_dir, ".gitkeep")
        if not os.path.exists(keep):
            with open(keep, "w") as f:
                f.write("")

    # Seed universal memory purity guardrail rule
    rules_tmpl = os.path.join(repo_root, "config", "memories", "rules", "memory_purity_guardrail.md")
    dest_rule = os.path.join(mem_dir, "rules", "memory_purity_guardrail.md")
    if os.path.exists(rules_tmpl) and not os.path.exists(dest_rule):
        shutil.copyfile(rules_tmpl, dest_rule)

    # Seed persona (SOUL.md) to both memory plane and Hermes runtime workspace
    persona_path = agent.get("persona")
    if persona_path and os.path.exists(os.path.join(repo_root, persona_path)):
        src_persona = os.path.join(repo_root, persona_path)
        shutil.copyfile(src_persona, os.path.join(mem_dir, "SOUL.md"))
        shutil.copyfile(src_persona, os.path.join(work_dir, "SOUL.md"))

    # Seed subagents if configured
    subagents = agent.get("subagents", [])
    subagents_mem_dir = os.path.join(mem_dir, "subagents")
    subagents_work_dir = os.path.join(work_dir, "subagents")
    if subagents:
        os.makedirs(subagents_mem_dir, exist_ok=True)
        os.makedirs(subagents_work_dir, exist_ok=True)
        for sub in subagents:
            sub_id = sub.get("id")
            sub_persona_path = sub.get("persona")
            if sub_id and sub_persona_path and os.path.exists(os.path.join(repo_root, sub_persona_path)):
                src_sub_persona = os.path.join(repo_root, sub_persona_path)
                dest_sub_mem = os.path.join(subagents_mem_dir, sub_id)
                dest_sub_work = os.path.join(subagents_work_dir, sub_id)
                os.makedirs(dest_sub_mem, exist_ok=True)
                os.makedirs(dest_sub_work, exist_ok=True)
                shutil.copyfile(src_sub_persona, os.path.join(dest_sub_mem, "SOUL.md"))
                shutil.copyfile(src_sub_persona, os.path.join(dest_sub_work, "SOUL.md"))
        with open(os.path.join(work_dir, "subagents.json"), "w", encoding="utf-8") as sf:
            json.dump(subagents, sf, indent=2)
        with open(os.path.join(mem_dir, "subagents.json"), "w", encoding="utf-8") as sf:
            json.dump(subagents, sf, indent=2)

    # Scaffold workspace sandbox (tools, skills, cron, and runtime memories)
    for sub in ("skills", "plugins", "signal", "cron", "memories"):
        os.makedirs(os.path.join(work_dir, sub), exist_ok=True)

    # Scaffold titan-subagents plugin into workspace if subagents configured
    if subagents:
        src_plugin = os.path.join(repo_root, "docker", "hermes", "plugins", "titan-subagents")
        dest_plugin = os.path.join(work_dir, "plugins", "titan-subagents")
        if os.path.exists(src_plugin):
            if os.path.exists(dest_plugin):
                shutil.rmtree(dest_plugin)
            shutil.copytree(src_plugin, dest_plugin)

    # Seed initial Hermes working memory files if not present
    ws_memories_dir = os.path.join(work_dir, "memories")
    mem_file = os.path.join(ws_memories_dir, "MEMORY.md")
    user_file = os.path.join(ws_memories_dir, "USER.md")
    if not os.path.exists(mem_file):
        with open(mem_file, "w", encoding="utf-8") as f:
            f.write(f"# {agent.get('name', agent_id)} — Working Memory\n\nActive context and execution notes.\n")
    if not os.path.exists(user_file):
        with open(user_file, "w", encoding="utf-8") as f:
            f.write(f"# User Profile\n\nFacts and preferences learned about the user.\n")

    keep = os.path.join(work_dir, ".gitkeep")
    if not os.path.exists(keep):
        with open(keep, "w") as f:
            f.write("")

    # Scaffold dedicated web app site / HTML canvas repository if configured
    if site_rel:
        site_dir = os.path.abspath(os.path.join(repo_root, site_rel.lstrip("./")))
        os.makedirs(site_dir, exist_ok=True)
        repo_url = agent.get("workspace", {}).get("repo_url")
        git_dir = os.path.join(site_dir, ".git")
        if repo_url and not os.path.exists(git_dir):
            import subprocess
            try:
                existing_items = [i for i in os.listdir(site_dir) if i != ".gitkeep"]
                if not existing_items:
                    keep_file = os.path.join(site_dir, ".gitkeep")
                    if os.path.exists(keep_file):
                        os.remove(keep_file)
                    subprocess.run(["git", "clone", repo_url, site_dir], check=True, capture_output=True)
                else:
                    subprocess.run(["git", "-C", site_dir, "init"], check=True, capture_output=True)
                    subprocess.run(["git", "-C", site_dir, "remote", "add", "origin", repo_url], check=True, capture_output=True)
                    subprocess.run(["git", "-C", site_dir, "fetch", "origin"], check=True, capture_output=True)
                    subprocess.run(["git", "-C", site_dir, "checkout", "-f", "main"], check=True, capture_output=True)
            except Exception as ge:
                print(f"[WARN] Git repository binding for {site_dir} encountered: {ge}")

        # Configure local git identity in site_dir if git config provided
        git_conf = agent.get("git", {})
        if os.path.exists(git_dir) and git_conf:
            import subprocess
            u_name = git_conf.get("user_name")
            u_email = git_conf.get("user_email")
            if u_name:
                subprocess.run(["git", "-C", site_dir, "config", "user.name", u_name], capture_output=True)
            if u_email:
                subprocess.run(["git", "-C", site_dir, "config", "user.email", u_email], capture_output=True)

    # Seed agent git config in work_dir if configured
    git_conf = agent.get("git", {})
    if git_conf:
        gitconfig_path = os.path.join(work_dir, ".gitconfig")
        u_name = git_conf.get("user_name", f"Agent {agent_id}")
        u_email = git_conf.get("user_email", f"{agent_id}@titan.local")
        proxy_host = git_conf.get("proxy_host", "github-proxy.titan.local")
        with open(gitconfig_path, "w", encoding="utf-8") as gf:
            gf.write(
                f"[user]\n\tname = {u_name}\n\temail = {u_email}\n"
                f"[credential]\n\thelper = !gh auth git-credential\n"
                f"[safe]\n\tdirectory = *\n"
                f"[url \"https://{proxy_host}/\"]\n\tinsteadOf = https://github.com/\n"
                f"[core]\n\taskPass = \"\"\n"
            )

    # Render Hermes cron jobs if configured
    cron_jobs = agent.get("cron", [])
    if cron_jobs:
        cron_file = os.path.join(work_dir, "cron", "jobs.json")
        jobs_data = []
        for c in cron_jobs:
            jobs_data.append({
                "id": c.get("id", f"{agent_id}-job"),
                "name": c.get("name", c.get("id")),
                "cron_expr": c.get("schedule", "0 2 * * *"),
                "prompt": c.get("prompt", ""),
                "enabled": True,
                "created_at": "2026-09-12T00:00:00Z"
            })
        with open(cron_file, "w", encoding="utf-8") as jf:
            json.dump(jobs_data, jf, indent=2)

    # Seed Hermes configuration with agent identity and default model
    tmpl_config = os.path.join(repo_root, "config", "hermes", "config.yaml")
    dest_config = os.path.join(work_dir, "config.yaml")
    if os.path.exists(tmpl_config):
        with open(tmpl_config, "r", encoding="utf-8") as tf:
            cfg = yaml.safe_load(tf)
        cfg["agent"] = {"name": agent_id}
        default_model = agent.get("models", {}).get("default")
        if default_model and "model" in cfg:
            cfg["model"]["default"] = default_model
        # Seed per-agent Telegram platform settings
        tg_config = agent.get("comms", {}).get("telegram", {})
        if "platforms" in cfg and "telegram" in cfg["platforms"]:
            cfg["platforms"]["telegram"]["enabled"] = tg_config.get("enabled", False)
            cfg["platforms"]["telegram"]["bot_name"] = tg_config.get("bot_name", f"@{agent_id}_bot")
        # Ensure titan-subagents plugin is enabled if subagents are configured
        if subagents:
            if "plugins" not in cfg:
                cfg["plugins"] = {"enabled": ["hermes-okf"]}
            if "enabled" not in cfg["plugins"]:
                cfg["plugins"]["enabled"] = ["hermes-okf"]
            if "titan-subagents" not in cfg["plugins"]["enabled"]:
                cfg["plugins"]["enabled"].append("titan-subagents")
        with open(dest_config, "w", encoding="utf-8") as df:
            yaml.safe_dump(cfg, df, sort_keys=False)

    # Seed initial gateway_state.json so s6 auto-starts gateway-default
    gw_state = os.path.join(work_dir, "gateway_state.json")
    if not os.path.exists(gw_state):
        with open(gw_state, "w", encoding="utf-8") as gf:
            gf.write('{"desired_state":"running","gateway_state":"running"}\n')

    print(f"[SUCCESS] Scaffolded host partitions for '{agent_id}':")
    print(f"  - Memory:    {mem_dir}")
    print(f"  - Workspace: {work_dir}")
    if site_rel:
        print(f"  - Site:      {os.path.abspath(os.path.join(repo_root, site_rel.lstrip('./')))}")

# 3B. Render dynamic SilverBullet PKM fleet memory index
index_lines = [
    "# Project Titan: Multi-Agent Fleet Memory Plane\n",
    "Welcome to the **Project Titan Memory Plane**—the human-auditable, decoupled knowledge and governance hub for autonomous agent execution.\n",
    "This workspace mounts the host filesystem (`/memories`) using the **Open Knowledge Format (OKF)**: pure, human-readable flat-file Markdown.\n",
    "---\n",
    "## 🧭 Multi-Agent Fleet Navigation\n"
]
for idx, a in enumerate(enabled_agents, 1):
    a_id = a["id"]
    a_name = a.get("name", a_id)
    index_lines.append(f"### {idx}. [[agents/{a_id}/SOUL|{a_name}]]\n")
    index_lines.append(f"- **Soul & Persona**: [[agents/{a_id}/SOUL|SOUL.md]]\n")
    subagents = a.get("subagents", [])
    for sub in subagents:
        sub_id = sub.get("id")
        sub_name = sub.get("name", sub_id)
        index_lines.append(f"  - **Sub-Agent ({sub_id})**: [[agents/{a_id}/subagents/{sub_id}/SOUL|{sub_name}]]\n")
    index_lines.append(f"- **Knowledge Base**: [[agents/{a_id}/knowledge/|knowledge/]]\n")
    index_lines.append(f"- **Operator Rules**: [[agents/{a_id}/rules/|rules/]]\n")
    index_lines.append(f"- **Session Logs**: [[agents/{a_id}/logs/|logs/]]\n")

index_lines.append("---\n")
index_lines.append("> [!NOTE]\n> **Memory Purity Enforcement**: Only Markdown (`.md`) files are allowed in this space. Binary files, SQLite databases, package caches, and virtualenvs are strictly barred to ensure zero-trust human auditability.\n")
index_content = "\n".join(index_lines)

for target_idx in [
    os.path.join(repo_root, "data", "memories", "index.md"),
    os.path.join(repo_root, "config", "memories", "index.md")
]:
    os.makedirs(os.path.dirname(target_idx), exist_ok=True)
    with open(target_idx, "w", encoding="utf-8") as f:
        f.write(index_content)
EOF

# 4. Enforce permissions (chmod 775 on workspaces/memories and preserve file executables)
chmod -R 775 "${REPO_ROOT}/data/workspace" "${REPO_ROOT}/data/memories" 2>/dev/null || true
if [ -d "${REPO_ROOT}/apps" ]; then
  find "${REPO_ROOT}/apps" -type d -exec chmod 775 {} + 2>/dev/null || true
  chmod -R ug+rw "${REPO_ROOT}/apps" 2>/dev/null || true
  if [ -d "${REPO_ROOT}/apps/cindypawford/infra/node_modules/.bin" ]; then
    chmod +x "${REPO_ROOT}/apps/cindypawford/infra/node_modules/.bin/"* 2>/dev/null || true
  fi
  if [ -f "${REPO_ROOT}/apps/cindypawford/infra/node_modules/typescript/bin/tsc" ]; then
    chmod +x "${REPO_ROOT}/apps/cindypawford/infra/node_modules/typescript/bin/tsc" 2>/dev/null || true
  fi
fi

# 5. Provision Virtual Keys
provision_virtual_keys

# 6. Reload or Restart Caddy Ingress if running
if docker compose ps -q caddy >/dev/null 2>&1 && [ -n "$(docker compose ps -q caddy 2>/dev/null)" ]; then
  log_info "Reloading Caddy ingress gateway to activate routes..."
  if ! docker compose exec -T caddy caddy reload --config /etc/caddy/Caddyfile 2>/dev/null; then
    log_info "Admin API disabled; ensuring Caddy container is up to date..."
    docker compose up -d --no-deps caddy >/dev/null 2>&1 || log_warn "Failed to update Caddy container."
  fi
fi

log_success "Multi-agent fleet synchronization complete!"
