#!/usr/bin/env bash
# ==============================================================================
# Project Titan: Multi-Agent Fleet Manifest Synchronization & Orchestration Engine
# Renders docker-compose.agents.yml and config/caddy/agents.caddy from config/agents.yaml.
# Scaffolds host storage partitions, permissions, and LiteLLM virtual keys.
# ==============================================================================

set -euo pipefail

# Visual styling
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${REPO_ROOT}"

# Load environment variables
if [ -f .env ]; then
  set -a
  . ./.env
  set +a
elif [ -f .env.example ]; then
  set -a
  . ./.env.example
  set +a
fi

MANIFEST_FILE="${REPO_ROOT}/config/agents.yaml"
OUTPUT_COMPOSE="${REPO_ROOT}/docker-compose.agents.yml"
OUTPUT_CADDY="${REPO_ROOT}/config/caddy/agents.caddy"

# Ensure python3 with yaml is available
PYTHON_BIN="python3"
if [ -x "${REPO_ROOT}/.venv/bin/python" ]; then
  PYTHON_BIN="${REPO_ROOT}/.venv/bin/python"
fi

if ! ${PYTHON_BIN} -c "import yaml" >/dev/null 2>&1; then
  log_error "Python PyYAML package is required to parse ${MANIFEST_FILE}."
  exit 1
fi

if [ ! -f "${MANIFEST_FILE}" ]; then
  log_error "Fleet manifest not found at ${MANIFEST_FILE}."
  exit 1
fi

MODE="${1:-sync}"

# ------------------------------------------------------------------------------
# Core Generator in Python
# ------------------------------------------------------------------------------
render_manifest() {
  ${PYTHON_BIN} - << 'EOF'
import os
import sys
import yaml

repo_root = os.getcwd()
manifest_path = os.path.join(repo_root, "config", "agents.yaml")

with open(manifest_path, "r", encoding="utf-8") as f:
    manifest = yaml.safe_load(f)

agents = manifest.get("agents", [])
enabled_agents = [a for a in agents if a.get("enabled", True)]

# 1. Render docker-compose.agents.yml
compose_lines = [
    "# ==============================================================================",
    "# Project Titan: Declarative Multi-Agent Fleet Services",
    "# Auto-generated by scripts/sync-agents.sh from config/agents.yaml.",
    "# DO NOT EDIT DIRECTLY. Make changes in config/agents.yaml and re-run sync.",
    "# ==============================================================================",
    "",
    "services:",
]

for agent in enabled_agents:
    agent_id = agent["id"]
    name = agent.get("name", f"Agent {agent_id}")
    runtime = agent.get("runtime", "hermes")
    port = agent.get("comms", {}).get("port", 8642)
    dash_port = agent.get("comms", {}).get("dashboard_port", 9119)
    signal_enabled = agent.get("comms", {}).get("signal", {}).get("enabled", False)
    telegram_enabled = agent.get("comms", {}).get("telegram", {}).get("enabled", False)

    mem_path = agent.get("memory", {}).get("path", f"./data/memories/tenants/{agent_id}")
    work_path = agent.get("workspace", {}).get("path", f"./data/workspace/{agent_id}")
    key_name = agent.get("routing", {}).get("virtual_key", f"HERMES_{agent_id.upper().replace('-', '_')}_KEY")

    compose_lines.extend([
        f"  # --------------------------------------------------------------------------",
        f"  # L6: Agent Core Unit: {name} ({agent_id})",
        f"  # --------------------------------------------------------------------------",
        f"  agent-{agent_id}:",
        f"    build:",
        f"      context: .",
        f"      dockerfile: docker/hermes/Dockerfile",
        f"    image: titan-hermes:latest",
        f"    container_name: titan-agent-{agent_id}",
        f"    restart: unless-stopped",
        f"    security_opt:",
        f"      - \"no-new-privileges:true\"",
        f"    ports:",
        f"      - \"127.0.0.1:{port}:{port}\"",
        f"      - \"127.0.0.1:{dash_port}:{dash_port}\"",
        f"    extra_hosts:",
        f"      - \"host.docker.internal:host-gateway\"",
        f"      - \"proxy.local:host-gateway\"",
        f"      - \"litellm:host-gateway\"",
        f"      - \"langfuse.titan.local:${{LANGFUSE_HOST_IP:-host-gateway}}\"",
        f"    volumes:",
        f"      # L5: Memory Plane (pure OKF markdown)",
        f"      - {mem_path}:/memories",
        f"      # Read-only configuration",
        f"      - ./config/hermes:/app/config:ro",
        f"      # L5: Unprivileged Workspace Sandbox",
        f"      - {work_path}:/opt/data",
        f"      - {work_path}:/workspace",
        f"    working_dir: /opt/data",
        f"    environment:",
        f"      - PUID=${{PUID:-1000}}",
        f"      - PGID=${{PGID:-1000}}",
        f"      - HERMES_DASHBOARD=1",
        f"      - HERMES_PORT={port}",
        f"      - HERMES_DASHBOARD_PORT={dash_port}",
        f"      - HERMES_DASHBOARD_BASIC_AUTH_USERNAME=${{HERMES_DASHBOARD_USER:-admin}}",
        f"      - HERMES_DASHBOARD_BASIC_AUTH_PASSWORD=${{HERMES_DASHBOARD_PASSWORD:-titan_admin_secret}}",
        f"      - HERMES_LITELLM_KEY=${{{key_name}:-sk-titan-{agent_id}-key}}",
        f"      - CUSTOM_API_KEY=${{{key_name}:-sk-titan-{agent_id}-key}}",
        f"      - OPENAI_API_KEY=${{{key_name}:-sk-titan-{agent_id}-key}}",
        f"      - OPENAI_BASE_URL=http://proxy.local:${{LITELLM_PORT:-4000}}/v1",
        f"      - PROXY_URL=http://proxy.local:${{LITELLM_PORT:-4000}}/v1",
        f"      - LITELLM_URL=http://proxy.local:${{LITELLM_PORT:-4000}}/v1",
        f"      - MEMORY_DIR=/memories",
        f"      - WORKSPACE_DIR=/opt/data",
        f"      - INFERENCE_NUM_CTX=${{INFERENCE_NUM_CTX:-4096}}",
        f"      - HERMES_GATEWAY_BOOTSTRAP_STATE=running",
        f"      - API_SERVER_HOST=0.0.0.0",
        f"      - API_SERVER_PORT={port}",
        f"      - API_SERVER_KEY=${{API_SERVER_KEY:-}}",
        f"      - SIGNAL_HTTP_URL=http://signal-cli:8080",
        f"      - SIGNAL_ACCOUNT=${{SIGNAL_ACCOUNT:-}}",
        f"      - SIGNAL_ALLOWED_USERS=${{SIGNAL_ALLOWED_USERS:-}}",
        f"      - TELEGRAM_BOT_TOKEN=${{TELEGRAM_BOT_TOKEN:-}}",
        f"      - TELEGRAM_ALLOWED_USERS=${{TELEGRAM_ALLOWED_USERS:-}}",
        f"      - LANGFUSE_OTEL_AUTH=${{LANGFUSE_OTEL_AUTH:-}}",
        f"    command: [\"sleep\", \"infinity\"]",
        f"    depends_on:",
        f"      - signal-cli",
        f"    networks:",
        f"      - titan-ingress",
        f"      - titan-internal",
        "",
    ])

# 2. Render config/caddy/agents.caddy
caddy_lines = [
    "# ==============================================================================",
    "# Project Titan: Ingress Reverse Proxy Routes for Agent Units (L7: Comms & UX)",
    "# Auto-generated by scripts/sync-agents.sh from config/agents.yaml.",
    "# DO NOT EDIT DIRECTLY. Make changes in config/agents.yaml and re-run sync.",
    "# ==============================================================================",
    "",
]

for agent in enabled_agents:
    agent_id = agent["id"]
    name = agent.get("name", f"Agent {agent_id}")
    port = agent.get("comms", {}).get("port", 8642)
    dash_port = agent.get("comms", {}).get("dashboard_port", 9119)
    subdomain = agent.get("comms", {}).get("subdomain", f"{agent_id}.titan.local")

    # For primary agent, support legacy aliases hermes.titan.local / hermes.localhost
    aliases = ""
    api_aliases = ""
    if agent_id == "primary":
        aliases = f", http://hermes.{{$TITAN_DOMAIN:titan.local}}, https://hermes.{{$TITAN_DOMAIN:titan.local}}, http://hermes.localhost, https://hermes.localhost"
        api_aliases = f", http://api.hermes.{{$TITAN_DOMAIN:titan.local}}, https://api.hermes.{{$TITAN_DOMAIN:titan.local}}, http://api.hermes.localhost, https://api.hermes.localhost"

    caddy_lines.extend([
        f"# ------------------------------------------------------------------------------",
        f"# Agent Unit: {name} ({agent_id}) - Dashboard & Console",
        f"# ------------------------------------------------------------------------------",
        f"http://{subdomain}, https://{subdomain}, http://{agent_id}.localhost, https://{agent_id}.localhost{aliases} {{",
        f"	tls internal",
        f"	encode gzip zstd",
        f"	log {{",
        f"		output stdout",
        f"		format console",
        f"	}}",
        f"	reverse_proxy titan-agent-{agent_id}:{dash_port} {{",
        f"		flush_interval -1",
        f"	}}",
        f"}}",
        f"",
        f"# ------------------------------------------------------------------------------",
        f"# Agent Unit: {name} ({agent_id}) - OpenAI-Compatible API",
        f"# ------------------------------------------------------------------------------",
        f"http://api.{subdomain}, https://api.{subdomain}, http://api.{agent_id}.localhost, https://api.{agent_id}.localhost{api_aliases} {{",
        f"	tls internal",
        f"	encode gzip zstd",
        f"	log {{",
        f"		output stdout",
        f"		format console",
        f"	}}",
        f"	reverse_proxy titan-agent-{agent_id}:{port} {{",
        f"		flush_interval -1",
        f"	}}",
        f"}}",
        f"",
    ])

rendered_compose = "\n".join(compose_lines).strip() + "\n"
rendered_caddy = "\n".join(caddy_lines).strip() + "\n"

# Output separator for bash parsing
print("__START_COMPOSE__")
sys.stdout.write(rendered_compose)
print("__END_COMPOSE__")
print("__START_CADDY__")
sys.stdout.write(rendered_caddy)
print("__END_CADDY__")
EOF
}

# ------------------------------------------------------------------------------
# Action: Drift Detection (--check)
# ------------------------------------------------------------------------------
if [ "${MODE}" = "--check" ]; then
  log_info "Verifying fleet manifest drift against rendered files..."
  
  RENDERED_OUTPUT=$(render_manifest)
  EXPECTED_COMPOSE=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_COMPOSE__/,/__END_COMPOSE__/p' | sed '1d;$d')
  EXPECTED_CADDY=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_CADDY__/,/__END_CADDY__/p' | sed '1d;$d')

  DRIFT_DETECTED=0

  if [ ! -f "${OUTPUT_COMPOSE}" ]; then
    log_error "Missing file: ${OUTPUT_COMPOSE}"
    DRIFT_DETECTED=1
  else
    ACTUAL_COMPOSE=$(cat "${OUTPUT_COMPOSE}")
    if [ "${ACTUAL_COMPOSE}" != "${EXPECTED_COMPOSE}" ]; then
      log_error "Drift detected in ${OUTPUT_COMPOSE}!"
      diff -u <(echo "${ACTUAL_COMPOSE}") <(echo "${EXPECTED_COMPOSE}") || true
      DRIFT_DETECTED=1
    fi
  fi

  if [ ! -f "${OUTPUT_CADDY}" ]; then
    log_error "Missing file: ${OUTPUT_CADDY}"
    DRIFT_DETECTED=1
  else
    ACTUAL_CADDY=$(cat "${OUTPUT_CADDY}")
    if [ "${ACTUAL_CADDY}" != "${EXPECTED_CADDY}" ]; then
      log_error "Drift detected in ${OUTPUT_CADDY}!"
      diff -u <(echo "${ACTUAL_CADDY}") <(echo "${EXPECTED_CADDY}") || true
      DRIFT_DETECTED=1
    fi
  fi

  if [ ${DRIFT_DETECTED} -eq 0 ]; then
    log_success "✓ Fleet configuration is 100% in sync with config/agents.yaml."
    exit 0
  else
    log_error "Fleet drift check failed! Please run './scripts/sync-agents.sh' to reconcile."
    exit 1
  fi
fi

# ------------------------------------------------------------------------------
# Helper: Provision Virtual Keys in LiteLLM Control Plane Database
# ------------------------------------------------------------------------------
provision_virtual_keys() {
  LITELLM_PORT="${LITELLM_PORT:-4000}"
  LITELLM_MASTER_KEY="${LITELLM_MASTER_KEY:-}"
  LITELLM_URL="http://127.0.0.1:${LITELLM_PORT}"

  if ! curl -s -o /dev/null -w "%{http_code}" "${LITELLM_URL}/health/liveness" | grep -qE '^(200|401|405)'; then
    log_info "LiteLLM control plane is not currently running. Virtual keys will be seeded upon control plane boot."
    return 0
  fi

  if [ -z "${LITELLM_MASTER_KEY}" ]; then
    log_warn "LITELLM_MASTER_KEY is unset; skipping LiteLLM virtual key seeding."
    return 0
  fi

  log_info "Provisioning fleet virtual keys in LiteLLM Control Plane (${LITELLM_URL})..."

  ${PYTHON_BIN} - << EOF
import os
import urllib.request
import json
import yaml

repo_root = os.getcwd()
manifest_path = os.path.join(repo_root, "config", "agents.yaml")
with open(manifest_path, "r", encoding="utf-8") as f:
    manifest = yaml.safe_load(f)

master_key = os.environ.get("LITELLM_MASTER_KEY", "")
litellm_url = "${LITELLM_URL}"

for agent in manifest.get("agents", []):
    agent_id = agent["id"]
    budget = float(agent.get("routing", {}).get("budget_monthly_usd", 25.0))
    key_name = agent.get("routing", {}).get("virtual_key", f"HERMES_{agent_id.upper().replace('-', '_')}_KEY")
    key_val = os.environ.get(key_name, f"sk-titan-{agent_id}-key")

    check_url = f"{litellm_url}/key/info?key={key_val}"
    req = urllib.request.Request(check_url, headers={"Authorization": f"Bearer {master_key}"})
    key_exists = False
    try:
        with urllib.request.urlopen(req) as resp:
            if resp.status == 200:
                key_exists = True
    except Exception:
        pass

    if not key_exists:
        gen_url = f"{litellm_url}/key/generate"
        payload = json.dumps({
            "key": key_val,
            "key_alias": f"titan-agent-{agent_id}",
            "max_budget": budget,
            "models": []
        }).encode("utf-8")
        gen_req = urllib.request.Request(
            gen_url,
            data=payload,
            headers={
                "Authorization": f"Bearer {master_key}",
                "Content-Type": "application/json"
            }
        )
        try:
            with urllib.request.urlopen(gen_req) as resp:
                print(f"[SUCCESS] Provisioned virtual key for agent '{agent_id}' (alias: titan-agent-{agent_id}, budget: \${budget:.2f}).")
        except Exception as e:
            print(f"[WARN] Failed to provision key for '{agent_id}': {e}")
    else:
        print(f"[INFO] Virtual key for agent '{agent_id}' is already registered in LiteLLM DB.")
EOF
}

if [ "${MODE}" = "--provision-keys" ]; then
  provision_virtual_keys
  exit 0
fi

# ------------------------------------------------------------------------------
# Action: Full Synchronization
# ------------------------------------------------------------------------------
log_info "Synchronizing Project Titan Multi-Agent Fleet from ${MANIFEST_FILE}..."

RENDERED_OUTPUT=$(render_manifest)
EXPECTED_COMPOSE=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_COMPOSE__/,/__END_COMPOSE__/p' | sed '1d;$d')
EXPECTED_CADDY=$(echo "${RENDERED_OUTPUT}" | sed -n '/__START_CADDY__/,/__END_CADDY__/p' | sed '1d;$d')

# 1. Write docker-compose.agents.yml
echo "${EXPECTED_COMPOSE}" > "${OUTPUT_COMPOSE}"
log_success "Rendered agent compose topology at ${OUTPUT_COMPOSE}."

# 2. Write config/caddy/agents.caddy
mkdir -p "${REPO_ROOT}/config/caddy"
echo "${EXPECTED_CADDY}" > "${OUTPUT_CADDY}"
log_success "Rendered Caddy ingress configuration at ${OUTPUT_CADDY}."

# 3. Scaffold host storage partitions & permissions for each agent
${PYTHON_BIN} - << 'EOF'
import os
import shutil
import yaml

repo_root = os.getcwd()
manifest_path = os.path.join(repo_root, "config", "agents.yaml")
with open(manifest_path, "r", encoding="utf-8") as f:
    manifest = yaml.safe_load(f)

for agent in manifest.get("agents", []):
    agent_id = agent["id"]
    mem_rel = agent.get("memory", {}).get("path", f"./data/memories/tenants/{agent_id}")
    work_rel = agent.get("workspace", {}).get("path", f"./data/workspace/{agent_id}")

    mem_dir = os.path.abspath(os.path.join(repo_root, mem_rel.lstrip("./")))
    work_dir = os.path.abspath(os.path.join(repo_root, work_rel.lstrip("./")))

    # Scaffold memory partition (OKF pure markdown structure)
    for sub in ("knowledge", "rules", "logs"):
        sub_dir = os.path.join(mem_dir, sub)
        os.makedirs(sub_dir, exist_ok=True)
        keep = os.path.join(sub_dir, ".gitkeep")
        if not os.path.exists(keep):
            with open(keep, "w") as f:
                f.write("")

    # Seed persona (SOUL.md) if configured and not yet present
    persona_path = agent.get("persona")
    soul_dest = os.path.join(mem_dir, "SOUL.md")
    if persona_path and os.path.exists(os.path.join(repo_root, persona_path)) and not os.path.exists(soul_dest):
        shutil.copyfile(os.path.join(repo_root, persona_path), soul_dest)

    # Scaffold workspace sandbox
    for sub in ("skills", "plugins", "signal"):
        os.makedirs(os.path.join(work_dir, sub), exist_ok=True)

    keep = os.path.join(work_dir, ".gitkeep")
    if not os.path.exists(keep):
        with open(keep, "w") as f:
            f.write("")

    # Seed Hermes configuration with tenant identity and api_server platform
    tmpl_config = os.path.join(repo_root, "config", "hermes", "config.yaml")
    dest_config = os.path.join(work_dir, "config.yaml")
    if os.path.exists(tmpl_config):
        with open(tmpl_config, "r", encoding="utf-8") as tf:
            cfg = yaml.safe_load(tf)
        cfg["agent"] = {"name": agent_id}
        with open(dest_config, "w", encoding="utf-8") as df:
            yaml.safe_dump(cfg, df, sort_keys=False)

    # Seed initial gateway_state.json so s6 auto-starts gateway-default
    gw_state = os.path.join(work_dir, "gateway_state.json")
    if not os.path.exists(gw_state):
        with open(gw_state, "w", encoding="utf-8") as gf:
            gf.write('{"desired_state":"running","gateway_state":"running"}\n')

    print(f"[SUCCESS] Scaffolded host partitions for '{agent_id}':")
    print(f"  - Memory:    {mem_dir}")
    print(f"  - Workspace: {work_dir}")
EOF

# 4. Enforce permissions (chmod 775)
chmod -R 775 "${REPO_ROOT}/data/workspace" "${REPO_ROOT}/data/memories" 2>/dev/null || true

# 5. Provision Virtual Keys
provision_virtual_keys

# 6. Reload Caddy Ingress if running
if docker compose ps -q caddy >/dev/null 2>&1 && [ -n "$(docker compose ps -q caddy 2>/dev/null)" ]; then
  log_info "Reloading Caddy ingress gateway to activate routes..."
  docker compose exec -T caddy caddy reload --config /etc/caddy/Caddyfile 2>/dev/null || log_warn "Caddy reload returned non-zero (gateway will apply on next restart)."
fi

log_success "Multi-agent fleet synchronization complete!"
